local VanillaEnhanced = _G.VanillaEnhanced

local STRINGS = {
    enUS = {
        ["module.quests"] = "Quests",
        ["module.targetThreat"] = "Target threat",
        ["module.bags"] = "Bags",
        ["module.merchants"] = "Merchants",

        ["options.main.subtitle"] = "Turn modules on or off and adjust their options.",
        ["options.main.showChatMessagePrefix.label"] = "Show addon name in chat",
        ["options.main.showChatMessagePrefix.help"] = "Prefix addon chat messages with Vanilla Enhanced.",

        ["options.quests.subtitle"] = "Improves the quest tracker, quest log, maps, and tooltips.",
        ["options.quests.enable.label"] = "Enable",
        ["options.quests.enable.help"] = "Turn on the quest tracker, map, and tooltip changes.",
        ["options.quests.keepQuestLogWithMap.label"] = "Show quest log with map",
        ["options.quests.keepQuestLogWithMap.help"] = "Open the quest log beside the world map when possible.",
        ["options.quests.enableQuestTrackerClicks.label"] = "Clickable quest tracker",
        ["options.quests.enableQuestTrackerClicks.help"] = "Click a watched quest to open it in your quest log.",
        ["options.quests.showMapMarkers.label"] = "Quest markers on maps",
        ["options.quests.showMapMarkers.help"] = "Show quest locations on the world map and minimap.",
        ["options.quests.showMinimapObjectiveAreas.label"] = "Objective areas on minimap",
        ["options.quests.showMinimapObjectiveAreas.help"] = "Show slay and loot objective areas on the minimap.",
        ["options.quests.showAvailableQuests.label"] = "Available quests on world map",
        ["options.quests.showAvailableQuests.help"] = "Show quest starters you may be able to accept on the world map.",
        ["options.quests.onlyShowNearbyAvailableQuests.label"] = "Only nearby available quests",
        ["options.quests.onlyShowNearbyAvailableQuests.help"] = "Limit available quest markers to starters within about 1200 yards of you.",
        ["options.quests.onlyShowAvailableQuestsAroundPlayerLevel.label"] = "Only available quests near my level",
        ["options.quests.onlyShowAvailableQuestsAroundPlayerLevel.help"] = "Limit available quest markers to quests roughly within your level range.",
        ["options.quests.showCompletedMapObjectives.label"] = "Completed objectives on maps",
        ["options.quests.showCompletedMapObjectives.help"] = "Keep finished objective locations visible. Turn-in locations still appear.",
        ["options.quests.showCompletedTooltipObjectives.label"] = "Completed objectives in tooltips",
        ["options.quests.showCompletedTooltipObjectives.help"] = "Keep tooltip hints for objectives you have already finished.",

        ["options.targetThreat.subtitle"] = "Shows your threat percentage on the target frame.",
        ["options.targetThreat.enable.label"] = "Enable",
        ["options.targetThreat.enable.help"] = "Show your threat percentage near the target frame.",
        ["options.targetThreat.alwaysShow.label"] = "Show out of combat",
        ["options.targetThreat.alwaysShow.help"] = "Keep the threat text visible when you have a target, even outside combat.",

        ["options.bags.subtitle"] = "Adds bag sorting options.",
        ["options.bags.sortEnabled.label"] = "Enable sorting",
        ["options.bags.sortEnabled.help"] = "Turn on bag sorting.",
        ["options.bags.showSortButton.label"] = "Sort button",
        ["options.bags.showSortButton.help"] = "Show a sort button near the backpack.",
        ["options.bags.autoSortAfterLoot.label"] = "Sort after looting",
        ["options.bags.autoSortAfterLoot.help"] = "Sort your bags after the loot window closes.",
        ["options.bags.autoSortAfterLootMode.label"] = "After-loot mode",
        ["options.bags.autoSortAfterLootMode.tidy"] = "Tidy",
        ["options.bags.autoSortAfterLootMode.full"] = "Full sort",
        ["options.bags.autoSortAfterLootMode.help"] = "Tidy groups newly looted items without fully reordering each group. Full sort applies your precise sort order after every loot.",
        ["options.bags.autoSortOnOpen.label"] = "Sort when bags open",
        ["options.bags.autoSortOnOpen.help"] = "Sort your bags when you open them.",
        ["options.bags.sortOrder.label"] = "Sort by",
        ["options.bags.sortOrder.category"] = "Category",
        ["options.bags.sortOrder.quality"] = "Quality",
        ["options.bags.sortOrder.name"] = "Name",
        ["options.bags.sortOrder.help"] = "Choose how items are ordered when the addon sorts your bags.",

        ["options.merchants.subtitle"] = "Adds merchant quality-of-life tools.",
        ["options.merchants.enable.label"] = "Enable",
        ["options.merchants.enable.help"] = "Turn on merchant features.",
        ["options.merchants.sellScraps.label"] = "Sell scraps",
        ["options.merchants.sellScraps.help"] = "Show a merchant button that sells items matched by the selected scrap strategy.",
        ["options.merchants.autoSellScraps.label"] = "Sell automatically",
        ["options.merchants.autoSellScraps.help"] = "Sell one safe batch of scraps when you open a merchant.",
        ["options.merchants.autoRepair.label"] = "Repair automatically",
        ["options.merchants.autoRepair.help"] = "Repair your equipment when you open a merchant that can repair.",
        ["options.merchants.safeManualSell.label"] = "Safe button sells",
        ["options.merchants.safeManualSell.help"] = "Limit button clicks to 12 scrap stacks so sold items stay easier to buy back.",
        ["options.merchants.sortBagsAfterSellingScraps.label"] = "Sort bags after selling",
        ["options.merchants.sortBagsAfterSellingScraps.help"] = "Sort your bags after scraps are sold. Requires the Bags module and bag sorting to be enabled.",
        ["options.merchants.safeAutoSell.label"] = "Safe automatic sells",
        ["options.merchants.safeAutoSell.help"] = "Limit automatic selling to 12 scrap stacks. Turn this off only if you want auto-sell to clear every matching scrap stack.",
        ["options.merchants.scrapStrategy.label"] = "Scrap strategy",
        ["options.merchants.scrapStrategy.poorSellable"] = "Poor sellable items",
        ["options.merchants.scrapStrategy.poorUnusableEquipment"] = "Poor + unusable equipment",
        ["options.merchants.scrapStrategy.poorLowConsumables"] = "Poor + low consumables",
        ["options.merchants.scrapStrategy.poorLowEquipment"] = "Poor + low equipment",
        ["options.merchants.scrapStrategy.smart"] = "Smart cleanup",
        ["options.merchants.scrapStrategy.help"] = "Choose which items count as scraps. Smart cleanup also includes unusable bound equipment, very low consumables, and bound equipment far below what you wear.",

        ["bags.sort.button"] = "Sort",
        ["bags.sort.tooltipTitle"] = "Sort bags",
        ["bags.sort.tooltipBody"] = "Sorts your backpack and equipped bags.",
        ["bags.sort.debugPrefix"] = "Bags debug: {message}",
        ["bags.sort.debugAutoSort"] = "auto sorting after {reason}",
        ["bags.sort.debugMove"] = "moving bag {sourceBag} slot {sourceSlot} to bag {targetBag} slot {targetSlot}",
        ["bags.sort.debugWaitLocked"] = "waiting for locked bag {bag} slot {slot}",
        ["bags.sort.debugIgnoreLocked"] = "ignoring locked bag {bag} slot {slot}",
        ["bags.sort.reasonTrigger"] = "trigger",
        ["bags.sort.reasonOpen"] = "opening bags",
        ["bags.sort.reasonLoot"] = "looting",
        ["bags.sort.reasonMerchant"] = "selling scraps",
        ["bags.sort.errorChanged"] = "Bag sorting stopped because item positions changed unexpectedly.",
        ["bags.sort.errorRunning"] = "Bag sorting is already running.",
        ["bags.sort.errorUnavailableClient"] = "Manual bag sorting is not available on this client.",
        ["bags.sort.errorCursor"] = "Bag sorting is unavailable while an item is on your cursor.",
        ["bags.sort.errorPickup"] = "Bag sorting stopped because an item could not be picked up.",
        ["bags.sort.errorMove"] = "Bag sorting stopped because an item could not be moved.",
        ["bags.sort.errorLocked"] = "Bag sorting stopped because bag {bag} slot {slot} stayed locked.",

        ["merchants.sellScraps.button"] = "Scraps",
        ["merchants.sellScraps.tooltipTitle"] = "Sell scraps",
        ["merchants.sellScraps.tooltipBody"] = "Sell {count} scrap items for {money}.",
        ["merchants.sellScraps.tooltipEmpty"] = "No sellable scraps found.",
        ["merchants.sellScraps.sold"] = "Sold scraps for {money}.",
        ["merchants.sellScraps.errorCursor"] = "Cannot sell scraps while an item is on your cursor.",
        ["merchants.autoRepair.repaired"] = "Repaired equipment for {money}.",
        ["merchants.autoRepair.notEnoughMoney"] = "Not enough money to repair equipment ({money} required).",

        ["quests.static.turnin"] = "Turn in",
        ["quests.static.available"] = "Available quest",
        ["quests.static.availableQuestLevel"] = "Level {level} quest available",
        ["quests.static.questLevel"] = "Quest level {level}",
        ["quests.static.requiresLevel"] = "Requires level {level}",
        ["quests.static.nearbyObjectives"] = "nearby objectives",
        ["quests.static.areaObjectives"] = "objective points in this area",
        ["quests.static.multipleObjectives"] = "Multiple objectives",
        ["quests.static.nearbyMarkers"] = "Nearby quests",
    },

    frFR = {
        ["module.quests"] = "Quêtes",
        ["module.targetThreat"] = "Menace",
        ["module.bags"] = "Sacs",
        ["module.merchants"] = "Marchands",

        ["options.main.subtitle"] = "Active ou désactive les modules et ajuste leurs options.",
        ["options.main.showChatMessagePrefix.label"] = "Afficher le nom de l'addon dans le chat",
        ["options.main.showChatMessagePrefix.help"] = "Préfixe les messages de l'addon avec Vanilla Enhanced.",

        ["options.quests.subtitle"] = "Améliore le suivi des quêtes, le journal, les cartes et les infobulles.",
        ["options.quests.enable.label"] = "Activer",
        ["options.quests.enable.help"] = "Active le suivi des quêtes, la carte et les changements d'infobulles.",
        ["options.quests.keepQuestLogWithMap.label"] = "Afficher le journal avec la carte",
        ["options.quests.keepQuestLogWithMap.help"] = "Ouvre le journal des quêtes à côté de la carte du monde lorsque c'est possible.",
        ["options.quests.enableQuestTrackerClicks.label"] = "Suivi des quêtes cliquable",
        ["options.quests.enableQuestTrackerClicks.help"] = "Ouvre une quête suivie dans votre journal lorsque vous cliquez dessus.",
        ["options.quests.showMapMarkers.label"] = "Marqueurs de quêtes sur les cartes",
        ["options.quests.showMapMarkers.help"] = "Affiche les emplacements de quêtes sur la carte du monde et la minicarte.",
        ["options.quests.showMinimapObjectiveAreas.label"] = "Zones d'objectifs sur la minicarte",
        ["options.quests.showMinimapObjectiveAreas.help"] = "Affiche les zones d'objectifs à tuer et à ramasser sur la minicarte.",
        ["options.quests.showAvailableQuests.label"] = "Quêtes disponibles sur la carte",
        ["options.quests.showAvailableQuests.help"] = "Affiche sur la carte du monde les donneurs de quêtes que vous pouvez peut-être accepter.",
        ["options.quests.onlyShowNearbyAvailableQuests.label"] = "Seulement les quêtes proches",
        ["options.quests.onlyShowNearbyAvailableQuests.help"] = "Limite les marqueurs de quêtes disponibles aux donneurs situés à environ 1200 mètres de vous.",
        ["options.quests.onlyShowAvailableQuestsAroundPlayerLevel.label"] = "Seulement les quêtes de mon niveau",
        ["options.quests.onlyShowAvailableQuestsAroundPlayerLevel.help"] = "Limite les marqueurs de quêtes disponibles aux quêtes proches de votre niveau.",
        ["options.quests.showCompletedMapObjectives.label"] = "Objectifs terminés sur les cartes",
        ["options.quests.showCompletedMapObjectives.help"] = "Garde visibles les emplacements des objectifs terminés. Les lieux de rendu restent affichés.",
        ["options.quests.showCompletedTooltipObjectives.label"] = "Objectifs terminés dans les infobulles",
        ["options.quests.showCompletedTooltipObjectives.help"] = "Garde les indices d'infobulle pour les objectifs déjà terminés.",

        ["options.targetThreat.subtitle"] = "Affiche votre pourcentage de menace près du cadre de la cible.",
        ["options.targetThreat.enable.label"] = "Activer",
        ["options.targetThreat.enable.help"] = "Affiche votre pourcentage de menace près du cadre de la cible.",
        ["options.targetThreat.alwaysShow.label"] = "Afficher hors combat",
        ["options.targetThreat.alwaysShow.help"] = "Garde le texte de menace visible quand vous avez une cible, même hors combat.",

        ["options.bags.subtitle"] = "Ajoute des options de tri des sacs.",
        ["options.bags.sortEnabled.label"] = "Activer le tri",
        ["options.bags.sortEnabled.help"] = "Active le tri des sacs.",
        ["options.bags.showSortButton.label"] = "Bouton de tri",
        ["options.bags.showSortButton.help"] = "Affiche un bouton de tri près du sac à dos.",
        ["options.bags.autoSortAfterLoot.label"] = "Trier après le butin",
        ["options.bags.autoSortAfterLootMode.label"] = "Mode apres butin",
        ["options.bags.autoSortAfterLootMode.tidy"] = "Rangement leger",
        ["options.bags.autoSortAfterLootMode.full"] = "Tri complet",
        ["options.bags.autoSortAfterLootMode.help"] = "Le rangement leger regroupe les objets sans retrier completement chaque groupe. Le tri complet applique votre ordre precis apres chaque butin.",
        ["options.bags.autoSortAfterLoot.help"] = "Trie automatiquement vos sacs après la fermeture de la fenêtre de butin.",
        ["options.bags.autoSortOnOpen.label"] = "Trier à l'ouverture des sacs",
        ["options.bags.autoSortOnOpen.help"] = "Trie automatiquement vos sacs quand vous les ouvrez.",
        ["options.bags.sortOrder.label"] = "Trier par",
        ["options.bags.sortOrder.category"] = "Catégorie",
        ["options.bags.sortOrder.quality"] = "Qualité",
        ["options.bags.sortOrder.name"] = "Nom",
        ["options.bags.sortOrder.help"] = "Choisit comment les objets sont triés.",

        ["options.merchants.subtitle"] = "Ajoute des outils pratiques chez les marchands.",
        ["options.merchants.enable.label"] = "Activer",
        ["options.merchants.enable.help"] = "Active les fonctions de marchand.",
        ["options.merchants.sellScraps.label"] = "Vendre la camelote",
        ["options.merchants.sellScraps.help"] = "Affiche un bouton chez les marchands pour vendre les objets inutiles.",
        ["options.merchants.autoSellScraps.label"] = "Vendre automatiquement",
        ["options.merchants.autoSellScraps.help"] = "Vend automatiquement les objets inutiles quand vous ouvrez un marchand.",
        ["options.merchants.autoRepair.label"] = "Réparer automatiquement",
        ["options.merchants.autoRepair.help"] = "Répare votre équipement quand vous ouvrez un marchand capable de réparer.",
        ["options.merchants.safeManualSell.label"] = "Vente manuelle sécurisée",
        ["options.merchants.safeManualSell.help"] = "Limite la vente manuelle à 12 piles. Si désactivé, vend tous les objets inutiles, mais certains ne peuvent pas être rachetés.",
        ["options.merchants.sortBagsAfterSellingScraps.label"] = "Trier après la vente",
        ["options.merchants.sortBagsAfterSellingScraps.help"] = "Trie les sacs après la vente de la camelote.",
        ["options.merchants.safeAutoSell.label"] = "Vente automatique sécurisée",
        ["options.merchants.safeAutoSell.help"] = "Limite la vente automatique à 12 piles. Si désactivé, vend automatiquement tous les objets inutiles, mais certains ne peuvent pas être rachetés.",
        ["options.merchants.scrapStrategy.label"] = "Stratégie de camelote",
        ["options.merchants.scrapStrategy.poorSellable"] = "Objets gris vendables",
        ["options.merchants.scrapStrategy.poorUnusableEquipment"] = "Gris + équipement inutilisable",
        ["options.merchants.scrapStrategy.poorLowConsumables"] = "Gris + consommables faibles",
        ["options.merchants.scrapStrategy.poorLowEquipment"] = "Gris + équipement faible",
        ["options.merchants.scrapStrategy.smart"] = "Nettoyage intelligent",
        ["options.merchants.scrapStrategy.help"] = "Choisit quels objets comptent comme camelote. Le nettoyage intelligent inclut aussi l'équipement lié inutilisable, les consommables très faibles et l'équipement lié bien inférieur au vôtre.",

        ["bags.sort.button"] = "Trier",
        ["bags.sort.tooltipTitle"] = "Trier les sacs",
        ["bags.sort.tooltipBody"] = "Trie votre sac à dos et vos sacs équipés.",
        ["bags.sort.debugPrefix"] = "Débogage des sacs : {message}",
        ["bags.sort.debugAutoSort"] = "tri automatique après {reason}",
        ["bags.sort.debugMove"] = "déplacement du sac {sourceBag} emplacement {sourceSlot} vers le sac {targetBag} emplacement {targetSlot}",
        ["bags.sort.debugIgnoreLocked"] = "sac verrouille ignore {bag} emplacement {slot}",
        ["bags.sort.debugWaitLocked"] = "attente du sac verrouillé {bag} emplacement {slot}",
        ["bags.sort.reasonTrigger"] = "déclenchement",
        ["bags.sort.reasonOpen"] = "ouverture des sacs",
        ["bags.sort.reasonLoot"] = "butin",
        ["bags.sort.reasonMerchant"] = "vente de la camelote",
        ["bags.sort.errorChanged"] = "Le tri des sacs s'est arrêté parce que les emplacements des objets ont changé de manière inattendue.",
        ["bags.sort.errorRunning"] = "Le tri des sacs est déjà en cours.",
        ["bags.sort.errorUnavailableClient"] = "Le tri manuel des sacs n'est pas disponible sur ce client.",
        ["bags.sort.errorCursor"] = "Le tri des sacs est indisponible tant qu'un objet est sur votre curseur.",
        ["bags.sort.errorPickup"] = "Le tri des sacs s'est arrêté parce qu'un objet n'a pas pu être ramassé.",
        ["bags.sort.errorMove"] = "Le tri des sacs s'est arrêté parce qu'un objet n'a pas pu être déplacé.",
        ["bags.sort.errorLocked"] = "Le tri des sacs s'est arrêté parce que le sac {bag} emplacement {slot} est resté verrouillé.",

        ["merchants.sellScraps.button"] = "Vendre la camelote",
        ["merchants.sellScraps.tooltipTitle"] = "Vendre la camelote",
        ["merchants.sellScraps.tooltipBody"] = "Vend {count} objets pour {money}.",
        ["merchants.sellScraps.tooltipEmpty"] = "Aucun objet à vendre.",
        ["merchants.sellScraps.sold"] = "Camelote vendue pour {money}.",
        ["merchants.sellScraps.errorCursor"] = "Impossible de vendre la camelote tant qu'un objet est sur votre curseur.",
        ["merchants.autoRepair.repaired"] = "Équipement réparé pour {money}.",
        ["merchants.autoRepair.notEnoughMoney"] = "Pas assez d'argent pour réparer l'équipement ({money} requis).",

        ["quests.static.turnin"] = "Rendre la quête",
        ["quests.static.available"] = "Quête disponible",
        ["quests.static.availableQuestLevel"] = "Quête de niveau {level} disponible",
        ["quests.static.questLevel"] = "Niveau de quête {level}",
        ["quests.static.requiresLevel"] = "Niveau {level} requis",
        ["quests.static.nearbyObjectives"] = "objectifs proches",
        ["quests.static.areaObjectives"] = "points d'objectif dans cette zone",
        ["quests.static.multipleObjectives"] = "Objectifs multiples",
        ["quests.static.nearbyMarkers"] = "Quêtes proches",
    },
}

VanillaEnhanced.localeStrings = STRINGS

function VanillaEnhanced:GetLocaleKey()
    local locale = type(GetLocale) == "function" and GetLocale() or "enUS"
    return locale == "frFR" and "frFR" or "enUS"
end

local function Lookup(locale, key)
    local strings = STRINGS[locale]
    return strings and strings[key] or nil
end

function VanillaEnhanced:T(key, vars)
    local text = Lookup(self:GetLocaleKey(), key) or Lookup("enUS", key) or key
    if type(vars) ~= "table" then
        return text
    end

    local localized = string.gsub(text, "{([%w_]+)}", function(name)
        local value = vars[name]
        if value == nil then
            return "{" .. name .. "}"
        end
        return tostring(value)
    end)
    return localized
end
