local VanillaEnhanced = _G.VanillaEnhanced

local STRINGS = {
    enUS = {
        ["module.quests"] = "Quests",
        ["module.map"] = "Map",
        ["module.targetThreat"] = "Target threat",
        ["module.training"] = "Training",
        ["module.professions"] = "Professions",
        ["module.bags"] = "Bags",
        ["module.merchants"] = "Merchants",

        ["options.main.subtitle"] = "Turns modules on or off and adjusts their options.",
        ["options.main.locale.label"] = "Language",
        ["options.main.locale.help"] = "Chooses which language Vanilla Enhanced uses. Auto follows your WoW client language when supported.",
        ["options.main.locale.auto"] = "Auto",
        ["options.main.locale.auto.description"] = "Uses French on frFR clients and English otherwise.",
        ["options.main.locale.enUS"] = "English",
        ["options.main.locale.enUS.description"] = "Forces addon text to English.",
        ["options.main.locale.frFR"] = "Français",
        ["options.main.locale.frFR.description"] = "Forces addon text to French.",
        ["options.main.configurationPreset.label"] = "Configuration preset",
        ["options.main.configurationPreset.help"] = "Adapt Vanilla Enhanced's options depending on your chosen playstyle.",
        ["options.main.configurationPreset.explorer"] = "Explorer",
        ["options.main.configurationPreset.explorer.description"] = "Keeps light quest UI conveniences while hiding objective guidance and map quest assistance.",
        ["options.main.configurationPreset.adventurer"] = "Adventurer",
        ["options.main.configurationPreset.adventurer.description"] = "Balances quest quality-of-life with world discovery by keeping fog-of-war limits enabled.",
        ["options.main.configurationPreset.guide"] = "Guide",
        ["options.main.configurationPreset.guide.description"] = "Enables broad quest guidance for players who want minimal quest reading and faster routing.",
        ["options.main.applyConfigurationPreset.label"] = "Apply preset",
        ["options.main.configurationPreset.applied"] = "{preset} preset applied.",
        ["options.main.chatMessagesEnabled.label"] = "Show chat messages",
        ["options.main.chatMessagesEnabled.help"] = "Allows Vanilla Enhanced features to print notifications and errors in chat.",
        ["options.main.showChatMessagePrefix.label"] = "Show the addon name in chat",
        ["options.main.showChatMessagePrefix.help"] = "Prefixes chat messages with Vanilla Enhanced.",
        ["options.main.resetSettings.label"] = "Reset settings",
        ["options.main.resetSettings.help"] = "Restores all Vanilla Enhanced options to their default values.",
        ["options.main.resetSettings.confirm"] = "Reset all Vanilla Enhanced settings to defaults?",
        ["options.main.resetSettings.accept"] = "Reset",
        ["options.main.resetSettings.cancel"] = "Cancel",
        ["options.main.resetSettings.done"] = "Settings reset to defaults.",

        ["options.quests.subtitle"] = "Improves the quest tracker, quest log, maps, and tooltips.",
        ["options.quests.enable.label"] = "Enable",
        ["options.quests.enable.help"] = "Turns on the quest tracker, map, and tooltip changes.",
        ["options.quests.section.tracker"] = "Quest log and tracker",
        ["options.quests.section.mapMarkers"] = "Map markers",
        ["options.quests.section.tooltips"] = "Tooltips",
        ["options.quests.keepQuestLogWithMap.label"] = "Show quest log with map",
        ["options.quests.keepQuestLogWithMap.help"] = "Opens the quest log beside the world map when possible.",
        ["options.quests.enableQuestTrackerClicks.label"] = "Clickable quest tracker",
        ["options.quests.enableQuestTrackerClicks.help"] = "Opens a watched quest in your quest log when you click it.",
        ["options.quests.autoFollowQuestsMode.label"] = "Auto-follow",
        ["options.quests.autoFollowQuestsMode.disabled"] = "Off",
        ["options.quests.autoFollowQuestsMode.disabled.description"] = "Leaves your watched quest list unchanged.",
        ["options.quests.autoFollowQuestsMode.movement"] = "Update while moving",
        ["options.quests.autoFollowQuestsMode.movement.description"] = "Keeps nearby quests automatically watched as you move.",
        ["options.quests.autoFollowQuestsMode.zone"] = "Update on zone change",
        ["options.quests.autoFollowQuestsMode.zone.description"] = "Updates active quests with known objectives in your current zone.",
        ["options.quests.autoFollowQuestsMode.help"] = "Chooses when automatic quest following updates. Manually watched quests are never removed.",
        ["options.quests.autoFollowQuestsRange.label"] = "Nearby quest range",
        ["options.quests.autoFollowQuestsRange.close"] = "Close (600 yd)",
        ["options.quests.autoFollowQuestsRange.close.description"] = "Only auto-follows objectives within about 600 yards.",
        ["options.quests.autoFollowQuestsRange.nearby"] = "Nearby (1200 yd)",
        ["options.quests.autoFollowQuestsRange.nearby.description"] = "Uses a balanced 1200 yard range for nearby quest objectives.",
        ["options.quests.autoFollowQuestsRange.wide"] = "Wide (2400 yd)",
        ["options.quests.autoFollowQuestsRange.wide.description"] = "Looks up to about 2400 yards away, useful in sparse zones.",
        ["options.quests.autoFollowQuestsRange.help"] = "Only used while moving. Auto-followed quests outside this range are removed; manually watched quests stay put.",
        ["options.quests.showMapMarkers.label"] = "Quest markers on maps",
        ["options.quests.showMapMarkers.help"] = "Shows quest locations on the world map and minimap.",
        ["options.quests.hideMapMarkersInFogOfWar.label"] = "Hide markers in fog of war",
        ["options.quests.hideMapMarkersInFogOfWar.help"] = "Hides world map quest markers when their location is still unexplored.",
        ["options.quests.showSelectedQuestDirection.label"] = "Selected quest direction",
        ["options.quests.showSelectedQuestDirection.help"] = "Shows the selected quest's nearest objective on the minimap.",
        ["options.quests.showIncompleteDungeonTurnins.label"] = "Incomplete dungeon turn-ins",
        ["options.quests.showIncompleteDungeonTurnins.help"] = "Shows dungeon quest turn-in markers on the world map before the quest is complete.",
        ["options.quests.showMinimapObjectiveAreas.label"] = "Objective areas on minimap",
        ["options.quests.showMinimapObjectiveAreas.help"] = "Shows slay and loot objective areas on the minimap.",
        ["options.quests.showRepeatableQuests.label"] = "Repeatable quests on maps",
        ["options.quests.showRepeatableQuests.help"] = "Shows repeatable quest markers on the world map and minimap.",
        ["options.quests.showReputationQuests.label"] = "Reputation turn-ins on maps",
        ["options.quests.showReputationQuests.help"] = "Shows reputation hand-in quest markers, such as city cloth donations, on the world map and minimap.",
        ["options.quests.showAvailableQuests.label"] = "Available quests on world map",
        ["options.quests.showAvailableQuests.help"] = "Shows quest starters you may be able to accept on the world map.",
        ["options.quests.onlyShowNearbyAvailableQuests.label"] = "Only nearby available quests",
        ["options.quests.onlyShowNearbyAvailableQuests.help"] = "Limits available quest markers to starters within about 1200 yards of you.",
        ["options.quests.onlyShowAvailableQuestsAroundPlayerLevel.label"] = "Only available quests near my level",
        ["options.quests.onlyShowAvailableQuestsAroundPlayerLevel.help"] = "Limits available quest markers to quests roughly within your level range.",
        ["options.quests.availableQuestLevelsBelowPlayer.label"] = "Levels below player",
        ["options.quests.availableQuestLevelsBelowPlayer.help"] = "Shows available quests up to this many levels below you.",
        ["options.quests.availableQuestLevelsAbovePlayer.label"] = "Levels above player",
        ["options.quests.availableQuestLevelsAbovePlayer.help"] = "Shows available quests up to this many levels above you.",
        ["options.quests.showCompletedMapObjectives.label"] = "Completed objectives on maps",
        ["options.quests.showCompletedMapObjectives.help"] = "Keeps finished objective locations visible. Turn-in locations still appear.",
        ["options.quests.showCompletedTooltipObjectives.label"] = "Completed objectives in tooltips",
        ["options.quests.showCompletedTooltipObjectives.help"] = "Keeps tooltip hints for objectives you have already finished.",
        ["options.quests.showObjectiveTooltipHints.label"] = "Objective hints in tooltips",
        ["options.quests.showObjectiveTooltipHints.help"] = "Adds quest objective hints to matching unit tooltips.",
        ["options.quests.alwaysShowTooltipDropRates.label"] = "Always show drop rates",
        ["options.quests.alwaysShowTooltipDropRates.help"] = "Shows item drop percentages in tooltips without requiring holding SHIFT.",

        ["options.map.subtitle"] = "Improves map interactions with custom markers and minimap directions.",
        ["options.map.enable.label"] = "Enable",
        ["options.map.enable.help"] = "Turns on map improvements, including custom markers placed with Alt-left-click.",
        ["options.map.showWorldMapMarkers.label"] = "Custom markers",
        ["options.map.showWorldMapMarkers.help"] = "Shows this character's saved custom markers on the world map.",
        ["options.map.showMinimapDirections.label"] = "Marker directions",
        ["options.map.showMinimapDirections.help"] = "Shows saved custom markers on the minimap and floats distant markers on the edge.",
        ["options.map.autoRemoveReachedMarkers.label"] = "Clear reached markers",
        ["options.map.autoRemoveReachedMarkers.help"] = "Automatically removes custom markers when you get near them.",
        ["options.map.reachedMarkerDistanceYards.label"] = "Marker clear distance",
        ["options.map.reachedMarkerDistanceYards.help"] = "Clears custom markers when you are within this distance.",
        ["options.map.reachedMarkerDistanceYards.value"] = "{value} yd",
        ["options.map.enableTomTomCommands.label"] = "TomTom-style /way commands",
        ["options.map.enableTomTomCommands.help"] = "Lets Vanilla Enhanced handle /way coordinates when TomTom is not installed. Disabled automatically when TomTom is detected.",
        ["options.map.clearMarkers.label"] = "Clear markers",
        ["options.map.clearMarkers.help"] = "Removes all custom map markers saved for this character.",

        ["options.targetThreat.subtitle"] = "Shows your threat percentage on the target frame.",
        ["options.targetThreat.enable.label"] = "Enable",
        ["options.targetThreat.enable.help"] = "Shows your threat percentage near the target frame.",
        ["options.targetThreat.alwaysShow.label"] = "Show out of combat",
        ["options.targetThreat.alwaysShow.help"] = "Keeps the threat text visible when you have a target, even outside combat.",

        ["options.training.subtitle"] = "Adds a spellbook tab for unlearned class trainer spells.",
        ["options.training.enable.label"] = "Enable",
        ["options.training.enable.help"] = "Shows unlearned class trainer spells in a dedicated spellbook tab.",
        ["options.training.displayMode.label"] = "Training tab spells",
        ["options.training.displayMode.help"] = "Chooses which trainer spells appear in the spellbook training tab.",
        ["options.training.displayMode.trainable"] = "Available spells",
        ["options.training.displayMode.trainable.description"] = "Shows only spells you can train at your current level with current prerequisites.",
        ["options.training.displayMode.allUnlearned"] = "All spells",
        ["options.training.displayMode.allUnlearned.description"] = "Shows every unlearned class trainer spell for your class, race, and faction.",
        ["training.spell.unknown"] = "Spell {spellID}",
        ["training.spellbook.tab"] = "Training",
        ["training.spellbook.level"] = "Level {level}",
        ["training.spellbook.page"] = "Page {page}/{pages}",
        ["training.state.trainable"] = "Available from your class trainer.",
        ["training.state.future"] = "Available at level {level}.",
        ["training.state.missingRequirement"] = "Requires a previous rank or prerequisite spell.",
        ["training.state.missingTalent"] = "Requires a talent you have not learned.",
        ["training.tooltip.cost"] = "Training cost: {cost}",
        ["training.error.combat"] = "Cannot show training pages while in combat.",

        ["options.professions.subtitle"] = "Adds recipe usage hints to item tooltips.",
        ["options.professions.enable.label"] = "Enable",
        ["options.professions.enable.help"] = "Shows whether items are used by profession recipes.",
        ["options.professions.displayMode.label"] = "Tooltip detail",
        ["options.professions.displayMode.help"] = "Chooses how recipe usage appears in item tooltips.",
        ["options.professions.displayMode.compact"] = "Compact",
        ["options.professions.displayMode.compact.description"] = "Shows profession names with matching recipe counts.",
        ["options.professions.displayMode.recipes"] = "Recipe names",
        ["options.professions.displayMode.recipes.description"] = "Shows matching recipe names.",
        ["options.professions.recipeScope.label"] = "Recipes shown",
        ["options.professions.recipeScope.help"] = "Chooses whether tooltips include every dataset recipe or only recipes your character knows.",
        ["options.professions.recipeScope.all"] = "All recipes",
        ["options.professions.recipeScope.all.description"] = "Shows every recipe in Vanilla Enhanced's profession data.",
        ["options.professions.recipeScope.known"] = "Known recipes",
        ["options.professions.recipeScope.known.description"] = "Shows only recipes detected as known by this character.",
        ["options.professions.professionScope.label"] = "Professions shown",
        ["options.professions.professionScope.help"] = "Chooses which professions can contribute recipe hints.",
        ["options.professions.professionScope.all"] = "All professions",
        ["options.professions.professionScope.all.description"] = "Shows recipes from every profession.",
        ["options.professions.professionScope.player"] = "My professions",
        ["options.professions.professionScope.player.description"] = "Shows only recipes from professions this character has learned.",
        ["options.professions.professionScope.playerSkill"] = "My skill level",
        ["options.professions.professionScope.playerSkill.description"] = "Shows only recipes from your professions that your current skill can use.",
        ["professions.tooltip.header"] = "Used in recipes",
        ["professions.tooltip.compactLine"] = "{profession} ({count} recipes, {known} known)",
        ["professions.tooltip.recipeLine"] = "  {recipe} x{quantity}",
        ["professions.tooltip.moreProfessions"] = "+{count} more professions",
        ["professions.tooltip.moreRecipes"] = "  +{count} more recipes",
        ["professions.tooltip.summaryLine"] = "Used by {count} professions",
        ["professions.tooltip.summaryLine.one"] = "Used by 1 profession",
        ["professions.tooltip.shiftHint"] = "Hold SHIFT to show more",
        ["professions.recipeFallback"] = "Recipe {spellID}",
        ["professions.professionFallback"] = "Profession {professionID}",

        ["options.bags.subtitle"] = "Adds bag controls, sorting, search, and item safety options.",
        ["options.bags.enable.label"] = "Enable",
        ["options.bags.enable.help"] = "Turns on bag controls, sorting, search, item locking, icons, and automatic bag opening.",
        ["options.bags.section.controls"] = "Bag controls",
        ["options.bags.section.sorting"] = "Sorting",
        ["options.bags.showSortButton.label"] = "Sort button",
        ["options.bags.showSortButton.help"] = "Shows sort buttons near the backpack and bank.",
        ["options.bags.showSearchField.label"] = "Search field",
        ["options.bags.showSearchField.help"] = "Shows search fields near the backpack and bank.",
        ["options.bags.enableItemLocking.label"] = "Item locking",
        ["options.bags.enableItemLocking.help"] = "Alt-left-click a bag item to lock or unlock its current stack. Locked stacks stay in place during sorting and cannot be moved or sold.",
        ["options.bags.showQuestIcon.label"] = "Quest item icon",
        ["options.bags.showQuestIcon.help"] = "Shows an icon on items related to quests.",
        ["options.bags.showScrapIcon.label"] = "Scrap icon",
        ["options.bags.showScrapIcon.help"] = "Shows an icon on scrap items.",
        ["options.bags.showScrapToggleButton.label"] = "Scrap mark button",
        ["options.bags.showScrapToggleButton.help"] = "Shows a bag button that toggles scrap mark mode. Requires merchant scrap selling. You can also Alt-right-click a bag item to mark or unmark it as scrap.",
        ["options.bags.autoSortAfterLoot.label"] = "Sort after looting",
        ["options.bags.autoSortAfterLoot.help"] = "Sorts your bags after the loot window closes.",
        ["options.bags.autoSortOnOpen.label"] = "Sort when bags open",
        ["options.bags.autoSortOnOpen.help"] = "Sorts your bags when you open them.",
        ["options.bags.autoSortOnClose.label"] = "Sort when bags close",
        ["options.bags.autoSortOnClose.help"] = "Sorts your bags when you close them.",
        ["options.bags.autoOpenMode.label"] = "Open bags with",
        ["options.bags.autoOpenMode.disabled"] = "Off",
        ["options.bags.autoOpenMode.disabled.description"] = "Leaves bag opening unchanged.",
        ["options.bags.autoOpenMode.character"] = "Character sheet",
        ["options.bags.autoOpenMode.character.description"] = "Opens all bags when you open the character sheet.",
        ["options.bags.autoOpenMode.merchant"] = "Merchant",
        ["options.bags.autoOpenMode.merchant.description"] = "Opens all bags when you open a merchant.",
        ["options.bags.autoOpenMode.both"] = "Character sheet and merchant",
        ["options.bags.autoOpenMode.both.description"] = "Opens all bags when you open either the character sheet or a merchant.",
        ["options.bags.autoOpenMode.help"] = "Chooses which windows automatically open all bags.",
        ["options.bags.sortOrder.label"] = "Sort by",
        ["options.bags.sortOrder.category"] = "Category",
        ["options.bags.sortOrder.category.description"] = "Groups similar item types first, keeps health and mana consumables together, then sorts by quality, level, and name.",
        ["options.bags.sortOrder.quality"] = "Quality",
        ["options.bags.sortOrder.quality.description"] = "Prioritizes higher-quality and higher-level items before type and name.",
        ["options.bags.sortOrder.help"] = "Chooses how items are ordered when sorting your bags.",
        ["options.bags.sortFillDirection.label"] = "Fill order",
        ["options.bags.sortFillDirection.backpackFirst"] = "Backpack first",
        ["options.bags.sortFillDirection.backpackFirst.description"] = "Places sorted carried items in the backpack before equipped bags.",
        ["options.bags.sortFillDirection.backpackLast"] = "Equipped bags first",
        ["options.bags.sortFillDirection.backpackLast.description"] = "Places sorted carried items in equipped bags before the backpack.",
        ["options.bags.sortFillDirection.help"] = "Chooses which carried bag slots are filled first during sorting.",
        ["options.bags.sortScrapsLast.label"] = "Sort scraps last",
        ["options.bags.sortScrapsLast.help"] = "Places scrap items at the end when sorting bags and bank items.",

        ["options.merchants.subtitle"] = "Adds merchant quality-of-life tools.",
        ["options.merchants.enable.label"] = "Enable",
        ["options.merchants.enable.help"] = "Turns on merchant features.",
        ["options.merchants.sellScraps.label"] = "Sell scraps",
        ["options.merchants.sellScraps.help"] = "Shows a merchant button that sells items matched by the selected scrap strategy.",
        ["options.merchants.autoSellScraps.label"] = "Sell automatically",
        ["options.merchants.autoSellScraps.help"] = "Sells one safe batch of scraps when you open a merchant.",
        ["options.merchants.autoRepair.label"] = "Repair automatically",
        ["options.merchants.autoRepair.help"] = "Repairs your equipment when you open a merchant that can repair.",
        ["options.merchants.safeManualSell.label"] = "Safe button sells",
        ["options.merchants.safeManualSell.help"] = "Limits button clicks to 12 scrap stacks so sold items stay easier to buy back.",
        ["options.merchants.sortBagsAfterSellingScraps.label"] = "Sort bags after selling",
        ["options.merchants.sortBagsAfterSellingScraps.help"] = "Sorts your bags after scraps are sold. Requires the Bags module to be enabled.",
        ["options.merchants.safeAutoSell.label"] = "Safe automatic sells",
        ["options.merchants.safeAutoSell.help"] = "Limits automatic selling to 12 scrap stacks. When disabled, auto-sell clears every matching scrap stack.",
        ["options.merchants.scrapStrategy.label"] = "Scrap strategy",
        ["options.merchants.scrapStrategy.poorSellable"] = "Poor sellable items",
        ["options.merchants.scrapStrategy.poorSellable.description"] = "Sells gray items with a vendor price, while leaving quest items and locked items alone.",
        ["options.merchants.scrapStrategy.lowLevel"] = "Low level cleanup",
        ["options.merchants.scrapStrategy.lowLevel.description"] = "Also sells unusable gear, very low-level consumables, and gear far below what you wear.",
        ["options.merchants.scrapStrategy.smart"] = "Smart cleanup",
        ["options.merchants.scrapStrategy.smart.description"] = "Uses low level cleanup and also sells trade goods that are not used by recipes from your professions.",
        ["options.merchants.scrapStrategy.help"] = "Chooses which items count as scraps. Smart cleanup takes your professions into account when deciding whether trade goods are useful.",

        ["bags.sort.button"] = "Sort",
        ["bags.sort.tooltipTitle"] = "Sort bags",
        ["bags.sort.tooltipBody"] = "Sorts your backpack and equipped bags.",
        ["bags.search.placeholder"] = "Search",
        ["bags.search.tooltipTitle"] = "Search bags",
        ["bags.search.tooltipBody"] = "Type to dim bag items whose name, type, or tooltip does not match.",
        ["bags.bank.sort.tooltipTitle"] = "Sort bank",
        ["bags.bank.sort.tooltipBody"] = "Sorts your main bank and bank bags.",
        ["bags.bank.stack.button"] = "Stack",
        ["bags.bank.stack.tooltipTitle"] = "Stack to bank",
        ["bags.bank.stack.tooltipBody"] = "Moves matching carried items into existing bank piles.",
        ["bags.bank.search.tooltipTitle"] = "Search bank",
        ["bags.bank.search.tooltipBody"] = "Type to dim bank items whose name, type, or tooltip does not match.",
        ["bags.sort.errorChanged"] = "Bag sorting stopped because your bag contents changed.",
        ["bags.sort.errorRunning"] = "Bag sorting is already running.",
        ["bags.sort.errorUnavailableClient"] = "Cannot sort bags on this client.",
        ["bags.sort.errorCombat"] = "Cannot sort bags while in combat.",
        ["bags.sort.errorCursor"] = "Cannot sort bags while an item is on your cursor.",
        ["bags.sort.errorPickup"] = "Bag sorting stopped because an item could not be picked up.",
        ["bags.sort.errorMove"] = "Bag sorting stopped because an item could not be moved.",
        ["bags.sort.errorLocked"] = "Bag sorting stopped because bag {bag} slot {slot} stayed locked.",
        ["bags.lock.locked"] = "Locked {item}.",
        ["bags.lock.unlocked"] = "Unlocked {item}.",
        ["bags.lock.cannotMove"] = "Cannot move this item while it is locked.",
        ["bags.lock.cannotSell"] = "Cannot sell this item while it is locked.",
        ["bags.lock.itemFallback"] = "item {itemID}",
        ["bags.lock.itemUnknown"] = "this item",

        ["merchants.sellScraps.button"] = "Scraps",
        ["merchants.sellScraps.tooltipTitle"] = "Sell scraps",
        ["merchants.sellScraps.tooltipBody"] = "Sell {count} scrap items for {money}.",
        ["merchants.sellScraps.tooltipEmpty"] = "No sellable scraps found.",
        ["merchants.sellScraps.sold"] = "Sold scraps for {money}.",
        ["merchants.sellScraps.errorCursor"] = "Cannot sell scraps while an item is on your cursor.",
        ["merchants.scrapMark.tooltipTitle"] = "Mark scraps",
        ["merchants.scrapMark.tooltipInactive"] = "Scrap mark mode is off.",
        ["merchants.scrapMark.tooltipActive"] = "Scrap mark mode is on.",
        ["merchants.scrapMark.tooltipBody"] = "Click bag items in mark mode, or Alt-right-click them anytime, to mark or unmark them as scraps.",
        ["merchants.scrapMark.marked"] = "Marked {item} as scrap.",
        ["merchants.scrapMark.unmarked"] = "Unmarked {item} as scrap.",
        ["merchants.scrapMark.cannotMark"] = "Cannot mark {item} as scrap.",
        ["merchants.scrapMark.itemFallback"] = "item {itemID}",
        ["merchants.scrapMark.itemUnknown"] = "this item",
        ["merchants.autoRepair.repaired"] = "Repaired equipment for {money}.",
        ["merchants.autoRepair.notEnoughMoney"] = "Cannot repair equipment ({money} required).",

        ["map.marker.tooltipTitle"] = "Custom marker",
        ["map.marker.tooltipCoordinates"] = "{x}, {y}",
        ["map.marker.tooltipCoordinatesWithDistance"] = "{x}, {y} |cff8f8f8f({distance})|r",
        ["map.marker.tooltipDistanceYards"] = "{distance} yd",
        ["map.tomtom.error.disabled"] = "TomTom-style /way commands are disabled.",
        ["map.tomtom.error.tomTomDetected"] = "TomTom is installed, so Vanilla Enhanced is not handling /way.",
        ["map.tomtom.error.invalid"] = "Use /way x y, /way zone x y, or /way #mapId x y.",
        ["map.tomtom.error.coordinates"] = "Coordinates must be between 0 and 100.",
        ["map.tomtom.error.currentMap"] = "Cannot find a current map for this waypoint.",
        ["map.tomtom.error.unknown"] = "Unknown map: {map}.",
        ["map.tomtom.error.ambiguous"] = "More than one map matches: {map}.",
        ["map.marker.added"] = "Added marker in {map} at {x}, {y}.",
        ["map.marker.removed"] = "Removed marker.",
        ["map.marker.cleared"] = "Cleared this character's map markers.",
        ["map.marker.clearConfirm"] = "Clear all custom map markers for this character?",
        ["map.marker.clearAccept"] = "Clear",
        ["map.marker.clearCancel"] = "Cancel",
        ["map.marker.unsupportedMap"] = "Cannot place a marker on this map.",
        ["map.marker.unknownMap"] = "Unknown map",

        ["quests.static.turnin"] = "Turn in",
        ["quests.static.available"] = "Available quest",
        ["quests.static.availableQuestLevel"] = "Level {level} quest available",
        ["quests.static.activeQuestLevel"] = "Level {level} quest in progress",
        ["quests.static.questLevel"] = "Quest level {level}",
        ["quests.static.moreNpcs"] = "+{count} more NPCs",
        ["quests.static.requiresLevel"] = "Requires level {level}",
        ["quests.static.nearbyObjectives"] = "nearby objectives",
        ["quests.static.areaObjectives"] = "objective points in this area",
        ["quests.static.multipleObjectives"] = "Multiple objectives",
        ["quests.static.nearbyMarkers"] = "Nearby quests",
        ["quests.static.objectiveDifferentLevel"] = "Objective is on a different level.",
    },

    frFR = {
        ["module.quests"] = "Quêtes",
        ["module.map"] = "Carte",
        ["module.targetThreat"] = "Menace",
        ["module.training"] = "Entraînement",
        ["module.professions"] = "Métiers",
        ["module.bags"] = "Sacs",
        ["module.merchants"] = "Marchands",

        ["options.main.subtitle"] = "Active ou désactive les modules et ajuste leurs options.",
        ["options.main.locale.label"] = "Langue",
        ["options.main.locale.help"] = "Choisit la langue utilisée par Vanilla Enhanced. Auto suit la langue du client WoW quand elle est prise en charge.",
        ["options.main.locale.auto"] = "Auto",
        ["options.main.locale.auto.description"] = "Utilise le français sur les clients frFR et l’anglais sinon.",
        ["options.main.locale.enUS"] = "English",
        ["options.main.locale.enUS.description"] = "Force les textes de l’addon en anglais.",
        ["options.main.locale.frFR"] = "Français",
        ["options.main.locale.frFR.description"] = "Force les textes de l’addon en français.",
        ["options.main.configurationPreset.label"] = "Préréglage",
        ["options.main.configurationPreset.help"] = "Défini les options de Vanilla Enhanced en fonction du style de jeu choisi.",
        ["options.main.configurationPreset.explorer"] = "Exploration",
        ["options.main.configurationPreset.explorer.description"] = "Garde quelques conforts d'interface pour les quêtes, tout en masquant l'aide aux objectifs et aux emplacements sur la carte.",
        ["options.main.configurationPreset.adventurer"] = "Aventure",
        ["options.main.configurationPreset.adventurer.description"] = "Équilibre les améliorations de confort des quêtes et la découverte du monde en gardant les limites du brouillard de guerre.",
        ["options.main.configurationPreset.guide"] = "Guide",
        ["options.main.configurationPreset.guide.description"] = "Active une aide étendue pour les quêtes afin de réduire la lecture et d'accélérer les trajets.",
        ["options.main.applyConfigurationPreset.label"] = "Appliquer",
        ["options.main.configurationPreset.applied"] = "Préréglage {preset} appliqué.",
        ["options.main.chatMessagesEnabled.label"] = "Afficher les messages",
        ["options.main.chatMessagesEnabled.help"] = "Autorise les fonctions de Vanilla Enhanced à afficher les notifications et erreurs dans le chat.",
        ["options.main.showChatMessagePrefix.label"] = "Afficher le nom dans le chat",
        ["options.main.showChatMessagePrefix.help"] = "Préfixe les messages de chat avec Vanilla Enhanced.",
        ["options.main.resetSettings.label"] = "Réinitialiser",
        ["options.main.resetSettings.help"] = "Restaure toutes les options de Vanilla Enhanced à leurs valeurs par défaut.",
        ["options.main.resetSettings.confirm"] = "Réinitialiser tous les réglages de Vanilla Enhanced ?",
        ["options.main.resetSettings.accept"] = "Réinitialiser",
        ["options.main.resetSettings.cancel"] = "Annuler",
        ["options.main.resetSettings.done"] = "Réglages réinitialisés.",

        ["options.quests.subtitle"] = "Améliore le suivi des quêtes, le journal, les cartes et les infobulles.",
        ["options.quests.enable.label"] = "Activer",
        ["options.quests.enable.help"] = "Active le suivi des quêtes, la carte et les changements d'infobulles.",
        ["options.quests.section.tracker"] = "Journal et suivi des quêtes",
        ["options.quests.section.mapMarkers"] = "Marqueurs de carte",
        ["options.quests.section.tooltips"] = "Infobulles",
        ["options.quests.keepQuestLogWithMap.label"] = "Afficher le journal avec la carte",
        ["options.quests.keepQuestLogWithMap.help"] = "Ouvre le journal des quêtes à côté de la carte du monde lorsque c'est possible.",
        ["options.quests.enableQuestTrackerClicks.label"] = "Suivi des quêtes cliquable",
        ["options.quests.enableQuestTrackerClicks.help"] = "Ouvre une quête suivie dans votre journal lorsque vous cliquez dessus.",
        ["options.quests.autoFollowQuestsMode.label"] = "Suivi automatique",
        ["options.quests.autoFollowQuestsMode.disabled"] = "Désactivé",
        ["options.quests.autoFollowQuestsMode.disabled.description"] = "Ne modifie pas la liste des quêtes suivies.",
        ["options.quests.autoFollowQuestsMode.movement"] = "Mettre à jour en déplacement",
        ["options.quests.autoFollowQuestsMode.movement.description"] = "Suit automatiquement les quêtes proches pendant vos déplacements.",
        ["options.quests.autoFollowQuestsMode.zone"] = "Mettre à jour au changement de zone",
        ["options.quests.autoFollowQuestsMode.zone.description"] = "Met à jour les quêtes actives avec des objectifs connus dans votre zone actuelle.",
        ["options.quests.autoFollowQuestsMode.help"] = "Choisit quand le suivi automatique des quêtes se met à jour. Les quêtes suivies manuellement ne sont jamais retirées.",
        ["options.quests.autoFollowQuestsRange.label"] = "Portée des quêtes proches",
        ["options.quests.autoFollowQuestsRange.close"] = "Proche (600 m)",
        ["options.quests.autoFollowQuestsRange.close.description"] = "Suit automatiquement seulement les objectifs à environ 600 mètres ou moins.",
        ["options.quests.autoFollowQuestsRange.nearby"] = "À proximité (1200 m)",
        ["options.quests.autoFollowQuestsRange.nearby.description"] = "Utilise une portée équilibrée de 1200 mètres pour les objectifs proches.",
        ["options.quests.autoFollowQuestsRange.wide"] = "Large (2400 m)",
        ["options.quests.autoFollowQuestsRange.wide.description"] = "Cherche jusqu'à environ 2400 mètres, utile dans les zones peu denses.",
        ["options.quests.autoFollowQuestsRange.help"] = "Les quêtes suivies automatiquement qui sortent de cette portée sont retirées.",
        ["options.quests.showMapMarkers.label"] = "Marqueurs de quêtes sur les cartes",
        ["options.quests.showMapMarkers.help"] = "Affiche les emplacements de quêtes sur la carte du monde et la minicarte.",
        ["options.quests.hideMapMarkersInFogOfWar.label"] = "Masquer dans le brouillard de guerre",
        ["options.quests.hideMapMarkersInFogOfWar.help"] = "Masque les marqueurs de quêtes placés dans des zones encore inexplorées.",
        ["options.quests.showSelectedQuestDirection.label"] = "Direction de la quête sélectionnée",
        ["options.quests.showSelectedQuestDirection.help"] = "Affiche l'objectif le plus proche de la quête sélectionnée sur la minicarte.",
        ["options.quests.showIncompleteDungeonTurnins.label"] = "Quêtes de donjon incomplètes",
        ["options.quests.showIncompleteDungeonTurnins.help"] = "Affiche les marqueurs de rendu des quêtes de donjon sur la carte du monde avant que la quête soit terminée.",
        ["options.quests.showMinimapObjectiveAreas.label"] = "Zones d'objectifs sur la minicarte",
        ["options.quests.showMinimapObjectiveAreas.help"] = "Affiche les zones d'objectifs à tuer et à ramasser sur la minicarte.",
        ["options.quests.showRepeatableQuests.label"] = "Quêtes répétables sur les cartes",
        ["options.quests.showRepeatableQuests.help"] = "Affiche les marqueurs de quêtes répétables sur la carte du monde et la minicarte.",
        ["options.quests.showReputationQuests.label"] = "Quêtes de réputation sur les cartes",
        ["options.quests.showReputationQuests.help"] = "Affiche les marqueurs de quêtes de don de réputation, comme les dons de tissu des capitales, sur la carte du monde et la minicarte.",
        ["options.quests.showAvailableQuests.label"] = "Quêtes disponibles sur la carte",
        ["options.quests.showAvailableQuests.help"] = "Affiche sur la carte du monde les donneurs de quêtes que vous pouvez peut-être accepter.",
        ["options.quests.onlyShowNearbyAvailableQuests.label"] = "Seulement les quêtes proches",
        ["options.quests.onlyShowNearbyAvailableQuests.help"] = "Limite les marqueurs de quêtes disponibles aux donneurs situés à environ 1200 mètres de vous.",
        ["options.quests.onlyShowAvailableQuestsAroundPlayerLevel.label"] = "Seulement les quêtes de mon niveau",
        ["options.quests.onlyShowAvailableQuestsAroundPlayerLevel.help"] = "Limite les marqueurs de quêtes disponibles aux quêtes proches de votre niveau.",
        ["options.quests.availableQuestLevelsBelowPlayer.label"] = "Tranche basse",
        ["options.quests.availableQuestLevelsBelowPlayer.help"] = "Affiche les quêtes disponibles jusqu'à cette différence de niveaux avec le vôtre.",
        ["options.quests.availableQuestLevelsAbovePlayer.label"] = "Tranche haute",
        ["options.quests.availableQuestLevelsAbovePlayer.help"] = "Affiche les quêtes disponibles jusqu'à cette différence de niveaux avec le vôtre.",
        ["options.quests.showCompletedMapObjectives.label"] = "Objectifs terminés sur les cartes",
        ["options.quests.showCompletedMapObjectives.help"] = "Garde visibles les emplacements des objectifs terminés. Les lieux de rendu restent affichés.",
        ["options.quests.showCompletedTooltipObjectives.label"] = "Objectifs terminés dans les infobulles",
        ["options.quests.showCompletedTooltipObjectives.help"] = "Garde les indices d'infobulle pour les objectifs déjà terminés.",
        ["options.quests.showObjectiveTooltipHints.label"] = "Indices d'objectif dans les infobulles",
        ["options.quests.showObjectiveTooltipHints.help"] = "Ajoute des indices d'objectif de quête aux infobulles des unités correspondantes.",
        ["options.quests.alwaysShowTooltipDropRates.label"] = "Toujours afficher les taux de butin",
        ["options.quests.alwaysShowTooltipDropRates.help"] = "Affiche les pourcentages de butin dans les infobulles des unités sans devoir maintenir MAJ.",

        ["options.map.subtitle"] = "Ajoute des fonctionnalités à la carte du monde.",
        ["options.map.enable.label"] = "Activer",
        ["options.map.enable.help"] = "Active les améliorations de la carte du monde.",
        ["options.map.showWorldMapMarkers.label"] = "Marqueurs",
        ["options.map.showWorldMapMarkers.help"] = "Active les marqueurs personnalisés. Alt-clic sur la carte du monde pour en créer ou en supprimer un.",
        ["options.map.showMinimapDirections.label"] = "Minicarte",
        ["options.map.showMinimapDirections.help"] = "Affiche les marqueurs sur la minicarte et place les marqueurs lointains sur le bord.",
        ["options.map.autoRemoveReachedMarkers.label"] = "Effacer les marqueurs atteints",
        ["options.map.autoRemoveReachedMarkers.help"] = "Supprime automatiquement les marqueurs personnalisés quand vous arrivez proches d'eux.",
        ["options.map.reachedMarkerDistanceYards.label"] = "Distance d'effacement",
        ["options.map.reachedMarkerDistanceYards.help"] = "Efface les marqueurs personnalisés quand vous êtes à cette distance ou moins.",
        ["options.map.reachedMarkerDistanceYards.value"] = "{value} mètres",
        ["options.map.enableTomTomCommands.label"] = "Commandes /way façon TomTom",
        ["options.map.enableTomTomCommands.help"] = "Permet à Vanilla Enhanced de gérer les coordonnées /way quand TomTom n'est pas installé. Désactivé automatiquement si TomTom est détecté.",
        ["options.map.clearMarkers.label"] = "Effacer les marqueurs",
        ["options.map.clearMarkers.help"] = "Supprime tous les marqueurs enregistrés pour ce personnage.",

        ["options.targetThreat.subtitle"] = "Affiche votre pourcentage de menace près du cadre de la cible.",
        ["options.targetThreat.enable.label"] = "Activer",
        ["options.targetThreat.enable.help"] = "Affiche votre pourcentage de menace près du cadre de la cible.",
        ["options.targetThreat.alwaysShow.label"] = "Afficher hors combat",
        ["options.targetThreat.alwaysShow.help"] = "Garde le texte de menace visible quand vous avez une cible, même hors combat.",

        ["options.training.subtitle"] = "Ajoute un onglet du grimoire pour les sorts de maître de classe non appris.",
        ["options.training.enable.label"] = "Activer",
        ["options.training.enable.help"] = "Affiche les sorts de maître de classe non appris dans un onglet dédié du grimoire.",
        ["options.training.displayMode.label"] = "Sorts de l'onglet",
        ["options.training.displayMode.help"] = "Choisit quels sorts de maître apparaissent dans l'onglet d'entraînement du grimoire.",
        ["options.training.displayMode.trainable"] = "Sorts disponibles",
        ["options.training.displayMode.trainable.description"] = "Affiche seulement les sorts que vous pouvez apprendre à votre niveau avec vos prérequis actuels.",
        ["options.training.displayMode.allUnlearned"] = "Tous les sorts",
        ["options.training.displayMode.allUnlearned.description"] = "Affiche tous les sorts de maître non appris pour votre classe, race et faction.",
        ["training.spell.unknown"] = "Sort {spellID}",
        ["training.spellbook.tab"] = "Entraînement",
        ["training.spellbook.level"] = "Niveau {level}",
        ["training.spellbook.page"] = "Page {page}/{pages}",
        ["training.state.trainable"] = "Disponible auprès de votre maître de classe.",
        ["training.state.future"] = "Disponible au niveau {level}.",
        ["training.state.missingRequirement"] = "Nécessite un rang précédent ou un sort prérequis.",
        ["training.state.missingTalent"] = "Nécessite un talent que vous n'avez pas appris.",
        ["training.tooltip.cost"] = "Coût d'entraînement : {cost}",
        ["training.error.combat"] = "Impossible d'afficher les pages d'entraînement en combat.",

        ["options.professions.subtitle"] = "Ajoute aux infobulles les recettes de métier qui utilisent les objets.",
        ["options.professions.enable.label"] = "Activer",
        ["options.professions.enable.help"] = "Indique si les objets sont utilisés par des recettes de métier.",
        ["options.professions.displayMode.label"] = "Détail des infobulles",
        ["options.professions.displayMode.help"] = "Choisit comment l'utilisation en recette apparaît dans les infobulles d'objet.",
        ["options.professions.displayMode.compact"] = "Compact",
        ["options.professions.displayMode.compact.description"] = "Affiche les noms des métiers avec le nombre de recettes correspondantes.",
        ["options.professions.displayMode.recipes"] = "Noms des recettes",
        ["options.professions.displayMode.recipes.description"] = "Affiche les noms des recettes correspondantes.",
        ["options.professions.recipeScope.label"] = "Recettes affichées",
        ["options.professions.recipeScope.help"] = "Choisit si les infobulles incluent toutes les recettes des données ou seulement celles de votre personnage.",
        ["options.professions.recipeScope.all"] = "Toutes les recettes",
        ["options.professions.recipeScope.all.description"] = "Affiche toutes les recettes présentes dans les données de Vanilla Enhanced.",
        ["options.professions.recipeScope.known"] = "Recettes connues",
        ["options.professions.recipeScope.known.description"] = "Affiche seulement les recettes détectées comme connues par ce personnage.",
        ["options.professions.professionScope.label"] = "Métiers affichés",
        ["options.professions.professionScope.help"] = "Choisit quels métiers peuvent ajouter des indications de recette.",
        ["options.professions.professionScope.all"] = "Tous les métiers",
        ["options.professions.professionScope.all.description"] = "Affiche les recettes de tous les métiers.",
        ["options.professions.professionScope.player"] = "Mes métiers",
        ["options.professions.professionScope.player.description"] = "Affiche seulement les recettes des métiers appris par ce personnage.",
        ["options.professions.professionScope.playerSkill"] = "Mon niveau de compétence",
        ["options.professions.professionScope.playerSkill.description"] = "Affiche seulement les recettes de vos métiers utilisables avec votre compétence actuelle.",
        ["professions.tooltip.header"] = "Ingrédient pour plusieurs recettes",
        ["professions.tooltip.compactLine"] = "{profession} ({count} recettes, {known} connues)",
        ["professions.tooltip.recipeLine"] = "  {recipe} x{quantity}",
        ["professions.tooltip.moreProfessions"] = "+{count} autres métiers",
        ["professions.tooltip.moreRecipes"] = "  +{count} autres recettes",
        ["professions.tooltip.summaryLine"] = "Utilisé par {count} métiers",
        ["professions.tooltip.summaryLine.one"] = "Utilisé par 1 métier",
        ["professions.tooltip.shiftHint"] = "Maintiens MAJUSCULE pour plus de détails",
        ["professions.recipeFallback"] = "Recette {spellID}",
        ["professions.professionFallback"] = "Métier {professionID}",

        ["options.bags.subtitle"] = "Ajoute des options pour les contrôles des sacs, le tri, la recherche et la sécurité des objets.",
        ["options.bags.enable.label"] = "Activer",
        ["options.bags.enable.help"] = "Active les contrôles des sacs, le tri, la recherche, le verrouillage, les icônes et l'ouverture automatique.",
        ["options.bags.section.controls"] = "Contrôles des sacs",
        ["options.bags.section.sorting"] = "Tri",
        ["options.bags.showSortButton.label"] = "Bouton de tri",
        ["options.bags.showSortButton.help"] = "Affiche des boutons de tri près du sac à dos et de la banque.",
        ["options.bags.showSearchField.label"] = "Champ de recherche",
        ["options.bags.showSearchField.help"] = "Affiche des champs de recherche près du sac à dos et de la banque.",
        ["options.bags.enableItemLocking.label"] = "Verrouillage des objets",
        ["options.bags.enableItemLocking.help"] = "Alt-clic gauche sur un objet du sac pour verrouiller ou déverrouiller sa pile actuelle. Les piles verrouillées restent en place pendant le tri et ne peuvent pas être déplacées ni vendues.",
        ["options.bags.showQuestIcon.label"] = "Icône d'objet de quête",
        ["options.bags.showQuestIcon.help"] = "Affiche une icône sur les objets liés aux quêtes.",
        ["options.bags.showScrapIcon.label"] = "Icône de camelote",
        ["options.bags.showScrapIcon.help"] = "Affiche une icône sur les objets inutiles.",
        ["options.bags.showScrapToggleButton.label"] = "Bouton de marquage",
        ["options.bags.showScrapToggleButton.help"] = "Affiche un bouton sur les sacs qui active le mode de marquage de la camelote. Nécessite la vente de camelote chez les marchands. Vous pouvez aussi faire Alt-clic droit sur un objet du sac pour le marquer ou le retirer de la camelote.",
        ["options.bags.autoSortAfterLoot.label"] = "Trier après le butin",
        ["options.bags.autoSortAfterLoot.help"] = "Trie automatiquement vos sacs après la fermeture de la fenêtre de butin.",
        ["options.bags.autoSortOnOpen.label"] = "Trier à l'ouverture des sacs",
        ["options.bags.autoSortOnOpen.help"] = "Trie automatiquement vos sacs quand vous les ouvrez.",
        ["options.bags.autoSortOnClose.label"] = "Trier à la fermeture des sacs",
        ["options.bags.autoSortOnClose.help"] = "Trie automatiquement vos sacs quand vous les fermez.",
        ["options.bags.autoOpenMode.label"] = "Ouvrir les sacs avec",
        ["options.bags.autoOpenMode.disabled"] = "Désactivé",
        ["options.bags.autoOpenMode.disabled.description"] = "Ne change pas l'ouverture des sacs.",
        ["options.bags.autoOpenMode.character"] = "Fiche de personnage",
        ["options.bags.autoOpenMode.character.description"] = "Ouvre tous les sacs quand vous ouvrez la fiche de personnage.",
        ["options.bags.autoOpenMode.merchant"] = "Marchand",
        ["options.bags.autoOpenMode.merchant.description"] = "Ouvre tous les sacs quand vous ouvrez un marchand.",
        ["options.bags.autoOpenMode.both"] = "Fiche et marchand",
        ["options.bags.autoOpenMode.both.description"] = "Ouvre tous les sacs quand vous ouvrez la fiche de personnage ou un marchand.",
        ["options.bags.autoOpenMode.help"] = "Choisit quelles fenêtres ouvrent automatiquement tous les sacs.",
        ["options.bags.sortOrder.label"] = "Trier par",
        ["options.bags.sortOrder.category"] = "Catégorie",
        ["options.bags.sortOrder.category.description"] = "Regroupe d'abord les types d'objets similaires, garde les consommables de vie et de mana ensemble, puis trie par qualité, niveau et nom.",
        ["options.bags.sortOrder.quality"] = "Qualité",
        ["options.bags.sortOrder.quality.description"] = "Priorise les objets de meilleure qualité et de plus haut niveau avant le type et le nom.",
        ["options.bags.sortOrder.help"] = "Choisit comment les objets sont triés.",
        ["options.bags.sortFillDirection.label"] = "Ordre de remplissage",
        ["options.bags.sortFillDirection.backpackFirst"] = "Sac à dos d'abord",
        ["options.bags.sortFillDirection.backpackFirst.description"] = "Place les objets triés dans le sac à dos avant les sacs équipés.",
        ["options.bags.sortFillDirection.backpackLast"] = "Sacs équipés d'abord",
        ["options.bags.sortFillDirection.backpackLast.description"] = "Place les objets triés dans les sacs équipés avant le sac à dos.",
        ["options.bags.sortFillDirection.help"] = "Choisit quels emplacements de sacs sont remplis en premier pendant le tri.",
        ["options.bags.sortScrapsLast.label"] = "Camelote à la fin",
        ["options.bags.sortScrapsLast.help"] = "Place les objets inutiles à la fin pendant le tri des sacs et de la banque.",

        ["options.merchants.subtitle"] = "Ajoute des outils pratiques chez les marchands.",
        ["options.merchants.enable.label"] = "Activer",
        ["options.merchants.enable.help"] = "Active les fonctions de marchand.",
        ["options.merchants.sellScraps.label"] = "Vendre la camelote",
        ["options.merchants.sellScraps.help"] = "Affiche un bouton chez les marchands pour vendre les objets inutiles.",
        ["options.merchants.autoSellScraps.label"] = "Vendre automatiquement",
        ["options.merchants.autoSellScraps.help"] = "Vend automatiquement les objets inutiles quand vous ouvrez un marchand.",
        ["options.merchants.autoRepair.label"] = "Réparer automatiquement",
        ["options.merchants.autoRepair.help"] = "Répare votre équipement quand vous ouvrez un marchand capable de réparer.",
        ["options.merchants.safeManualSell.label"] = "Vente manuelle sécurisée",
        ["options.merchants.safeManualSell.help"] = "Limite la vente manuelle à 12 piles. Quand cette option est désactivée, la vente manuelle vend tous les objets inutiles, mais certains ne peuvent pas être rachetés.",
        ["options.merchants.sortBagsAfterSellingScraps.label"] = "Trier après la vente",
        ["options.merchants.sortBagsAfterSellingScraps.help"] = "Trie les sacs apres la vente de la camelote. Necessite que le module Sacs soit actif.",
        ["options.merchants.safeAutoSell.label"] = "Vente automatique sécurisée",
        ["options.merchants.safeAutoSell.help"] = "Limite la vente automatique à 12 piles. Quand cette option est désactivée, la vente automatique vend tous les objets inutiles, mais certains ne peuvent pas être rachetés.",
        ["options.merchants.scrapStrategy.label"] = "Stratégie de camelote",
        ["options.merchants.scrapStrategy.poorSellable"] = "Objets gris vendables",
        ["options.merchants.scrapStrategy.poorSellable.description"] = "Vend les objets gris ayant un prix de vente, en laissant les objets de quête et verrouillés.",
        ["options.merchants.scrapStrategy.lowLevel"] = "Nettoyage bas niveau",
        ["options.merchants.scrapStrategy.lowLevel.description"] = "Vend aussi l'équipement inutilisable, les consommables de très bas niveau et l'équipement très inférieur au vôtre.",
        ["options.merchants.scrapStrategy.smart"] = "Nettoyage intelligent",
        ["options.merchants.scrapStrategy.smart.description"] = "Utilise le nettoyage bas niveau et vend aussi les marchandises qui ne servent à aucune recette de vos métiers.",
        ["options.merchants.scrapStrategy.help"] = "Choisit quels objets comptent comme camelote. Le nettoyage intelligent tient compte de vos métiers pour décider si les marchandises sont utiles.",

        ["bags.sort.button"] = "Trier",
        ["bags.sort.tooltipTitle"] = "Trier les sacs",
        ["bags.sort.tooltipBody"] = "Trie votre sac à dos et vos sacs équipés.",
        ["bags.search.placeholder"] = "Rechercher",
        ["bags.search.tooltipTitle"] = "Rechercher dans les sacs",
        ["bags.search.tooltipBody"] = "Saisissez du texte pour assombrir les objets dont le nom, le type ou l'infobulle ne correspond pas.",
        ["bags.bank.sort.tooltipTitle"] = "Trier la banque",
        ["bags.bank.sort.tooltipBody"] = "Trie votre banque principale et vos sacs de banque.",
        ["bags.bank.stack.button"] = "Empiler",
        ["bags.bank.stack.tooltipTitle"] = "Empiler vers la banque",
        ["bags.bank.stack.tooltipBody"] = "Déplace les objets portés correspondants vers les piles existantes de la banque.",
        ["bags.bank.search.tooltipTitle"] = "Rechercher dans la banque",
        ["bags.bank.search.tooltipBody"] = "Saisissez du texte pour assombrir les objets de banque dont le nom, le type ou l'infobulle ne correspond pas.",
        ["bags.sort.errorChanged"] = "Le tri des sacs s'est arrêté parce que le contenu des sacs a changé.",
        ["bags.sort.errorRunning"] = "Le tri des sacs est déjà en cours.",
        ["bags.sort.errorUnavailableClient"] = "Impossible de trier les sacs sur ce client.",
        ["bags.sort.errorCombat"] = "Impossible de trier les sacs en combat.",
        ["bags.sort.errorCursor"] = "Impossible de trier les sacs tant qu'un objet est sur votre curseur.",
        ["bags.sort.errorPickup"] = "Le tri des sacs s'est arrêté parce qu'un objet n'a pas pu être ramassé.",
        ["bags.sort.errorMove"] = "Le tri des sacs s'est arrêté parce qu'un objet n'a pas pu être déplacé.",
        ["bags.sort.errorLocked"] = "Le tri des sacs s'est arrêté parce que le sac {bag} emplacement {slot} est resté verrouillé.",
        ["bags.lock.locked"] = "{item} verrouillé.",
        ["bags.lock.unlocked"] = "{item} déverrouillé.",
        ["bags.lock.cannotMove"] = "Impossible de déplacer cet objet tant qu'il est verrouillé.",
        ["bags.lock.cannotSell"] = "Impossible de vendre cet objet tant qu'il est verrouillé.",
        ["bags.lock.itemFallback"] = "objet {itemID}",
        ["bags.lock.itemUnknown"] = "cet objet",

        ["merchants.sellScraps.button"] = "Vendre la camelote",
        ["merchants.sellScraps.tooltipTitle"] = "Vendre la camelote",
        ["merchants.sellScraps.tooltipBody"] = "Vend {count} objets pour {money}.",
        ["merchants.sellScraps.tooltipEmpty"] = "Aucun objet à vendre.",
        ["merchants.sellScraps.sold"] = "Camelote vendue pour {money}.",
        ["merchants.sellScraps.errorCursor"] = "Impossible de vendre la camelote tant qu'un objet est sur votre curseur.",
        ["merchants.scrapMark.tooltipTitle"] = "Marquer la camelote",
        ["merchants.scrapMark.tooltipInactive"] = "Le mode de marquage est désactivé.",
        ["merchants.scrapMark.tooltipActive"] = "Le mode de marquage est activé.",
        ["merchants.scrapMark.tooltipBody"] = "En mode de marquage, cliquez sur les objets du sac, ou faites Alt-clic droit à tout moment, pour les marquer ou les retirer de la camelote.",
        ["merchants.scrapMark.marked"] = "{item} marqué comme camelote.",
        ["merchants.scrapMark.unmarked"] = "{item} retiré de la camelote.",
        ["merchants.scrapMark.cannotMark"] = "Impossible de marquer {item} comme camelote.",
        ["merchants.scrapMark.itemFallback"] = "objet {itemID}",
        ["merchants.scrapMark.itemUnknown"] = "cet objet",
        ["merchants.autoRepair.repaired"] = "Équipement réparé pour {money}.",
        ["merchants.autoRepair.notEnoughMoney"] = "Impossible de réparer l'équipement ({money} requis).",

        ["map.marker.tooltipTitle"] = "Marqueur",
        ["map.marker.tooltipCoordinates"] = "{x}, {y}",
        ["map.marker.tooltipCoordinatesWithDistance"] = "{x}, {y} |cff8f8f8f({distance})|r",
        ["map.marker.tooltipDistanceYards"] = "à {distance} mètres",
        ["map.tomtom.error.disabled"] = "Les commandes /way façon TomTom sont désactivées.",
        ["map.tomtom.error.tomTomDetected"] = "TomTom est installé, Vanilla Enhanced ne gère donc pas /way.",
        ["map.tomtom.error.invalid"] = "Utilisez /way x y, /way zone x y ou /way #idCarte x y.",
        ["map.tomtom.error.coordinates"] = "Les coordonnées doivent être comprises entre 0 et 100.",
        ["map.tomtom.error.currentMap"] = "Impossible de trouver une carte actuelle pour ce repère.",
        ["map.tomtom.error.unknown"] = "Carte inconnue : {map}.",
        ["map.tomtom.error.ambiguous"] = "Plusieurs cartes correspondent : {map}.",
        ["map.marker.added"] = "Marqueur ajouté dans {map} à {x}, {y}.",
        ["map.marker.removed"] = "Marqueur supprimé.",
        ["map.marker.cleared"] = "Marqueurs de carte effacés pour ce personnage.",
        ["map.marker.clearConfirm"] = "Effacer tous les marqueurs personnalisés de ce personnage ?",
        ["map.marker.clearAccept"] = "Effacer",
        ["map.marker.clearCancel"] = "Annuler",
        ["map.marker.unsupportedMap"] = "Impossible de placer un marqueur sur cette carte.",
        ["map.marker.unknownMap"] = "Carte inconnue",

        ["quests.static.turnin"] = "Rendre la quête",
        ["quests.static.available"] = "Quête disponible",
        ["quests.static.availableQuestLevel"] = "Quête de niveau {level} disponible",
        ["quests.static.activeQuestLevel"] = "Quête de niveau {level} en cours",
        ["quests.static.questLevel"] = "Niveau de quête {level}",
        ["quests.static.moreNpcs"] = "+{count} PNJ supplémentaires",
        ["quests.static.requiresLevel"] = "Niveau {level} requis",
        ["quests.static.nearbyObjectives"] = "objectifs proches",
        ["quests.static.areaObjectives"] = "points d'objectif dans cette zone",
        ["quests.static.multipleObjectives"] = "Objectifs multiples",
        ["quests.static.nearbyMarkers"] = "Quêtes proches",
        ["quests.static.objectiveDifferentLevel"] = "L'objectif est à un autre étage.",
    },
}

VanillaEnhanced.localeStrings = STRINGS

local FALLBACK_LOCALE = "enUS"
local IMPLEMENTED_LOCALES = { FALLBACK_LOCALE, "frFR" }
local SUPPORTED_LOCALES = {}
local LOCALE_OPTION_DEFINITIONS = {
    {
        value = "auto",
        labelKey = "options.main.locale.auto",
        descriptionKey = "options.main.locale.auto.description",
    },
    {
        value = "enUS",
        labelKey = "options.main.locale.enUS",
        descriptionKey = "options.main.locale.enUS.description",
    },
    {
        value = "frFR",
        labelKey = "options.main.locale.frFR",
        descriptionKey = "options.main.locale.frFR.description",
    },
}
local localeState = {
    stored = nil,
    effective = nil,
    activeStrings = nil,
    fallbackStrings = STRINGS[FALLBACK_LOCALE],
    dirty = true,
}

for _, locale in ipairs(IMPLEMENTED_LOCALES) do
    SUPPORTED_LOCALES[locale] = true
end

local function NormalizeLocaleSetting(locale)
    if locale ~= "auto" and not SUPPORTED_LOCALES[locale] then
        return "auto"
    end
    return locale
end

local function GetAutoLocaleKey()
    local locale = type(GetLocale) == "function" and GetLocale() or FALLBACK_LOCALE
    return locale == "frFR" and "frFR" or FALLBACK_LOCALE
end

local function GetStoredLocaleSetting(addon)
    local settings = addon.GetSettings and addon:GetSettings() or nil
    return NormalizeLocaleSetting(settings and settings.locale or "auto")
end

function VanillaEnhanced:RefreshLocaleState(force)
    if not force and not localeState.dirty and localeState.effective then
        return localeState.effective
    end

    local stored = GetStoredLocaleSetting(self)
    local effective = stored ~= "auto" and stored or GetAutoLocaleKey()

    localeState.stored = stored
    localeState.effective = effective
    localeState.activeStrings = STRINGS[effective] or localeState.fallbackStrings
    localeState.fallbackStrings = STRINGS[FALLBACK_LOCALE]
    localeState.dirty = false

    return localeState.effective
end

function VanillaEnhanced:GetLocaleKey()
    return self:RefreshLocaleState()
end

function VanillaEnhanced:SetLocaleKey(locale)
    locale = NormalizeLocaleSetting(locale)

    local settings = self:GetSettings()
    settings.locale = locale
    self:RefreshLocaleState(true)
    return settings.locale
end

function VanillaEnhanced:GetLocaleOptions()
    local options = {}
    for _, option in ipairs(LOCALE_OPTION_DEFINITIONS) do
        options[#options + 1] = {
            value = option.value,
            labelKey = option.labelKey,
            descriptionKey = option.descriptionKey,
        }
    end

    return options
end

local function Lookup(strings, key)
    return strings and strings[key] or nil
end

function VanillaEnhanced:T(key, vars)
    self:RefreshLocaleState()

    local text = Lookup(localeState.activeStrings, key) or Lookup(localeState.fallbackStrings, key) or key
    if type(vars) ~= "table" then
        return text
    end

    local localized = string.gsub(text, "{([%w_]+)}", function(name)
        local value = vars[name]
        if value == nil then
            return "{" .. name .. "}"
        end
        return tostring(value)
    end)
    return localized
end
