local VanillaEnhanced = _G.VanillaEnhanced

local STRINGS = {
    enUS = {
        ["module.quests"] = "Quests",
        ["module.map"] = "Map",
        ["module.targetThreat"] = "Target threat",
        ["module.bags"] = "Bags",
        ["module.merchants"] = "Merchants",

        ["options.main.subtitle"] = "Turns modules on or off and adjusts their options.",
        ["options.main.locale.label"] = "Language",
        ["options.main.locale.help"] = "Chooses which language Vanilla Enhanced uses. Auto follows your WoW client language when supported.",
        ["options.main.locale.auto"] = "Auto",
        ["options.main.locale.auto.description"] = "Uses French on frFR clients and English otherwise.",
        ["options.main.locale.enUS"] = "English",
        ["options.main.locale.enUS.description"] = "Forces addon text to English.",
        ["options.main.locale.frFR"] = "Français",
        ["options.main.locale.frFR.description"] = "Forces addon text to French.",
        ["options.main.chatMessagesEnabled.label"] = "Show chat messages",
        ["options.main.chatMessagesEnabled.help"] = "Allows Vanilla Enhanced features to print notifications and errors in chat.",
        ["options.main.showChatMessagePrefix.label"] = "Show the addon name in chat",
        ["options.main.showChatMessagePrefix.help"] = "Prefixes chat messages with Vanilla Enhanced.",
        ["options.main.resetSettings.label"] = "Reset settings",
        ["options.main.resetSettings.help"] = "Restores all Vanilla Enhanced options to their default values.",
        ["options.main.resetSettings.confirm"] = "Reset all Vanilla Enhanced settings to defaults?",
        ["options.main.resetSettings.accept"] = "Reset",
        ["options.main.resetSettings.cancel"] = "Cancel",
        ["options.main.resetSettings.done"] = "Settings reset to defaults.",

        ["options.quests.subtitle"] = "Improves the quest tracker, quest log, maps, and tooltips.",
        ["options.quests.enable.label"] = "Enable",
        ["options.quests.enable.help"] = "Turns on the quest tracker, map, and tooltip changes.",
        ["options.quests.keepQuestLogWithMap.label"] = "Show quest log with map",
        ["options.quests.keepQuestLogWithMap.help"] = "Opens the quest log beside the world map when possible.",
        ["options.quests.enableQuestTrackerClicks.label"] = "Clickable quest tracker",
        ["options.quests.enableQuestTrackerClicks.help"] = "Opens a watched quest in your quest log when you click it.",
        ["options.quests.autoFollowQuestsMode.label"] = "Auto-follow",
        ["options.quests.autoFollowQuestsMode.disabled"] = "Off",
        ["options.quests.autoFollowQuestsMode.disabled.description"] = "Leaves your watched quest list unchanged.",
        ["options.quests.autoFollowQuestsMode.movement"] = "Update while moving",
        ["options.quests.autoFollowQuestsMode.movement.description"] = "Checks nearby active quests as you move, limited by a short distance and time throttle.",
        ["options.quests.autoFollowQuestsMode.zone"] = "Update on zone change",
        ["options.quests.autoFollowQuestsMode.zone.description"] = "Updates nearby active quests when your zone or area changes.",
        ["options.quests.autoFollowQuestsMode.help"] = "Chooses when the quest tracker updates with nearby active quests.",
        ["options.quests.autoFollowQuestsBehavior.label"] = "Auto-follow behavior",
        ["options.quests.autoFollowQuestsBehavior.replaceDistant"] = "Replace distant quests",
        ["options.quests.autoFollowQuestsBehavior.replaceDistant.description"] = "Keeps nearby quests watched by replacing watched quests that are farther away.",
        ["options.quests.autoFollowQuestsBehavior.autoOnly"] = "Only manage auto-followed",
        ["options.quests.autoFollowQuestsBehavior.autoOnly.description"] = "Only replaces quests previously auto-followed; manually watched quests stay put.",
        ["options.quests.autoFollowQuestsBehavior.fillEmpty"] = "Fill empty slots only",
        ["options.quests.autoFollowQuestsBehavior.fillEmpty.description"] = "Adds nearby quests only when the tracker has open watch slots.",
        ["options.quests.autoFollowQuestsBehavior.help"] = "Chooses how automatic following interacts with quests already watched in your tracker.",
        ["options.quests.autoFollowQuestsRange.label"] = "Nearby quest range",
        ["options.quests.autoFollowQuestsRange.close"] = "Close (600 yd)",
        ["options.quests.autoFollowQuestsRange.close.description"] = "Only auto-follows objectives within about 600 yards.",
        ["options.quests.autoFollowQuestsRange.nearby"] = "Nearby (1200 yd)",
        ["options.quests.autoFollowQuestsRange.nearby.description"] = "Uses a balanced 1200 yard range for nearby quest objectives.",
        ["options.quests.autoFollowQuestsRange.wide"] = "Wide (2400 yd)",
        ["options.quests.autoFollowQuestsRange.wide.description"] = "Looks up to about 2400 yards away, useful in sparse zones.",
        ["options.quests.autoFollowQuestsRange.help"] = "Only auto-follows quests with known objectives inside this range. Leaves quests with unknown locations alone.",
        ["options.quests.showMapMarkers.label"] = "Quest markers on maps",
        ["options.quests.showMapMarkers.help"] = "Shows quest locations on the world map and minimap.",
        ["options.quests.hideMapMarkersInFogOfWar.label"] = "Hide markers in fog of war",
        ["options.quests.hideMapMarkersInFogOfWar.help"] = "Hides world map quest markers when their location is still unexplored.",
        ["options.quests.showSelectedQuestDirection.label"] = "Selected quest direction",
        ["options.quests.showSelectedQuestDirection.help"] = "Shows the selected quest's nearest objective on the minimap.",
        ["options.quests.showMinimapObjectiveAreas.label"] = "Objective areas on minimap",
        ["options.quests.showMinimapObjectiveAreas.help"] = "Shows slay and loot objective areas on the minimap.",
        ["options.quests.showRepeatableQuests.label"] = "Repeatable quests on maps",
        ["options.quests.showRepeatableQuests.help"] = "Shows repeatable quest markers on the world map and minimap.",
        ["options.quests.showAvailableQuests.label"] = "Available quests on world map",
        ["options.quests.showAvailableQuests.help"] = "Shows quest starters you may be able to accept on the world map.",
        ["options.quests.onlyShowNearbyAvailableQuests.label"] = "Only nearby available quests",
        ["options.quests.onlyShowNearbyAvailableQuests.help"] = "Limits available quest markers to starters within about 1200 yards of you.",
        ["options.quests.onlyShowAvailableQuestsAroundPlayerLevel.label"] = "Only available quests near my level",
        ["options.quests.onlyShowAvailableQuestsAroundPlayerLevel.help"] = "Limits available quest markers to quests roughly within your level range.",
        ["options.quests.availableQuestLevelsBelowPlayer.label"] = "Levels below player",
        ["options.quests.availableQuestLevelsBelowPlayer.help"] = "Shows available quests up to this many levels below you.",
        ["options.quests.availableQuestLevelsAbovePlayer.label"] = "Levels above player",
        ["options.quests.availableQuestLevelsAbovePlayer.help"] = "Shows available quests up to this many levels above you.",
        ["options.quests.showCompletedMapObjectives.label"] = "Completed objectives on maps",
        ["options.quests.showCompletedMapObjectives.help"] = "Keeps finished objective locations visible. Turn-in locations still appear.",
        ["options.quests.showCompletedTooltipObjectives.label"] = "Completed objectives in tooltips",
        ["options.quests.showCompletedTooltipObjectives.help"] = "Keeps tooltip hints for objectives you have already finished.",

        ["options.map.subtitle"] = "Improves map interactions with custom markers and minimap directions.",
        ["options.map.enable.label"] = "Enable",
        ["options.map.enable.help"] = "Turns on map improvements, including custom markers placed with Alt-left-click.",
        ["options.map.showWorldMapMarkers.label"] = "Custom markers",
        ["options.map.showWorldMapMarkers.help"] = "Shows this character's saved custom markers on the world map.",
        ["options.map.showMinimapDirections.label"] = "Marker directions",
        ["options.map.showMinimapDirections.help"] = "Shows saved custom markers on the minimap and floats distant markers on the edge.",
        ["options.map.enableTomTomCommands.label"] = "TomTom-style /way commands",
        ["options.map.enableTomTomCommands.help"] = "Lets Vanilla Enhanced handle /way coordinates when TomTom is not installed. Disabled automatically when TomTom is detected.",
        ["options.map.clearMarkers.label"] = "Clear markers",
        ["options.map.clearMarkers.help"] = "Removes all custom map markers saved for this character.",

        ["options.targetThreat.subtitle"] = "Shows your threat percentage on the target frame.",
        ["options.targetThreat.enable.label"] = "Enable",
        ["options.targetThreat.enable.help"] = "Shows your threat percentage near the target frame.",
        ["options.targetThreat.alwaysShow.label"] = "Show out of combat",
        ["options.targetThreat.alwaysShow.help"] = "Keeps the threat text visible when you have a target, even outside combat.",

        ["options.bags.subtitle"] = "Adds bag sorting and item locking options.",
        ["options.bags.enable.label"] = "Enable",
        ["options.bags.enable.help"] = "Turns on bag sorting features.",
        ["options.bags.showSortButton.label"] = "Sort button",
        ["options.bags.showSortButton.help"] = "Shows a sort button near the backpack.",
        ["options.bags.showSearchField.label"] = "Search field",
        ["options.bags.showSearchField.help"] = "Shows a bag search field next to the sort button. Typing dims items that do not match.",
        ["options.bags.enableItemLocking.label"] = "Item locking",
        ["options.bags.enableItemLocking.help"] = "Alt-left-click a bag item to lock or unlock its current stack. Locked stacks stay in place during sorting and cannot be moved or sold.",
        ["options.bags.showScrapIcon.label"] = "Scrap icon",
        ["options.bags.showScrapIcon.help"] = "Shows a small icon on bag items matched by the selected merchant scrap strategy.",
        ["options.bags.showScrapToggleButton.label"] = "Scrap mark button",
        ["options.bags.showScrapToggleButton.help"] = "Shows a bag button that toggles scrap mark mode. Requires scrap icons.",
        ["options.bags.autoSortAfterLoot.label"] = "Sort after looting",
        ["options.bags.autoSortAfterLoot.help"] = "Sorts your bags after the loot window closes.",
        ["options.bags.autoSortAfterLootMode.label"] = "After-loot mode",
        ["options.bags.autoSortAfterLootMode.tidy"] = "Tidy",
        ["options.bags.autoSortAfterLootMode.tidy.description"] = "Groups newly looted items without fully reordering every bag group.",
        ["options.bags.autoSortAfterLootMode.full"] = "Full sort",
        ["options.bags.autoSortAfterLootMode.full.description"] = "Runs the normal full sort after looting, using your selected sort order.",
        ["options.bags.autoSortAfterLootMode.help"] = "Tidy groups newly looted items without fully reordering each group. Full sort applies your precise sort order after every loot.",
        ["options.bags.autoSortOnOpen.label"] = "Sort when bags open",
        ["options.bags.autoSortOnOpen.help"] = "Sorts your bags when you open them.",
        ["options.bags.autoOpenMode.label"] = "Open bags with",
        ["options.bags.autoOpenMode.disabled"] = "Off",
        ["options.bags.autoOpenMode.disabled.description"] = "Leaves bag opening unchanged.",
        ["options.bags.autoOpenMode.character"] = "Character sheet",
        ["options.bags.autoOpenMode.character.description"] = "Opens all bags when you open the character sheet.",
        ["options.bags.autoOpenMode.merchant"] = "Merchant",
        ["options.bags.autoOpenMode.merchant.description"] = "Opens all bags when you open a merchant.",
        ["options.bags.autoOpenMode.both"] = "Character sheet and merchant",
        ["options.bags.autoOpenMode.both.description"] = "Opens all bags when you open either the character sheet or a merchant.",
        ["options.bags.autoOpenMode.help"] = "Chooses which windows automatically open all bags.",
        ["options.bags.sortOrder.label"] = "Sort by",
        ["options.bags.sortOrder.category"] = "Category",
        ["options.bags.sortOrder.category.description"] = "Groups similar item types first, then quality, level, and name.",
        ["options.bags.sortOrder.quality"] = "Quality",
        ["options.bags.sortOrder.quality.description"] = "Prioritizes higher-quality and higher-level items before type and name.",
        ["options.bags.sortOrder.name"] = "Name",
        ["options.bags.sortOrder.name.description"] = "Sorts alphabetically first, then uses type, quality, and level as tie-breakers.",
        ["options.bags.sortOrder.help"] = "Chooses how items are ordered when sorting your bags.",

        ["options.merchants.subtitle"] = "Adds merchant quality-of-life tools.",
        ["options.merchants.enable.label"] = "Enable",
        ["options.merchants.enable.help"] = "Turns on merchant features.",
        ["options.merchants.sellScraps.label"] = "Sell scraps",
        ["options.merchants.sellScraps.help"] = "Shows a merchant button that sells items matched by the selected scrap strategy.",
        ["options.merchants.autoSellScraps.label"] = "Sell automatically",
        ["options.merchants.autoSellScraps.help"] = "Sells one safe batch of scraps when you open a merchant.",
        ["options.merchants.autoRepair.label"] = "Repair automatically",
        ["options.merchants.autoRepair.help"] = "Repairs your equipment when you open a merchant that can repair.",
        ["options.merchants.safeManualSell.label"] = "Safe button sells",
        ["options.merchants.safeManualSell.help"] = "Limits button clicks to 12 scrap stacks so sold items stay easier to buy back.",
        ["options.merchants.sortBagsAfterSellingScraps.label"] = "Sort bags after selling",
        ["options.merchants.sortBagsAfterSellingScraps.help"] = "Sorts your bags after scraps are sold. Requires the Bags module to be enabled.",
        ["options.merchants.safeAutoSell.label"] = "Safe automatic sells",
        ["options.merchants.safeAutoSell.help"] = "Limits automatic selling to 12 scrap stacks. When disabled, auto-sell clears every matching scrap stack.",
        ["options.merchants.scrapStrategy.label"] = "Scrap strategy",
        ["options.merchants.scrapStrategy.poorSellable"] = "Poor sellable items",
        ["options.merchants.scrapStrategy.poorSellable.description"] = "Sells gray items with a vendor price, while leaving quest items and locked items alone.",
        ["options.merchants.scrapStrategy.poorUnusableEquipment"] = "Poor + unusable equipment",
        ["options.merchants.scrapStrategy.poorUnusableEquipment.description"] = "Also sells bound uncommon-or-lower equipment you cannot use.",
        ["options.merchants.scrapStrategy.poorLowConsumables"] = "Poor + low consumables",
        ["options.merchants.scrapStrategy.poorLowConsumables.description"] = "Also sells very low-level uncommon-or-lower consumables.",
        ["options.merchants.scrapStrategy.poorLowEquipment"] = "Poor + low equipment",
        ["options.merchants.scrapStrategy.poorLowEquipment.description"] = "Also sells bound uncommon-or-lower equipment far below what you wear.",
        ["options.merchants.scrapStrategy.smart"] = "Smart cleanup",
        ["options.merchants.scrapStrategy.smart.description"] = "Combines all cleanup rules: gray sellables, unusable gear, low consumables, and low gear.",
        ["options.merchants.scrapStrategy.help"] = "Chooses which items count as scraps. Smart cleanup also includes unusable bound equipment, very low consumables, and bound equipment far below what you wear.",

        ["bags.sort.button"] = "Sort",
        ["bags.sort.tooltipTitle"] = "Sort bags",
        ["bags.sort.tooltipBody"] = "Sorts your backpack and equipped bags.",
        ["bags.search.placeholder"] = "Search",
        ["bags.search.tooltipTitle"] = "Search bags",
        ["bags.search.tooltipBody"] = "Type to dim bag items whose name, type, or tooltip does not match.",
        ["bags.sort.errorChanged"] = "Bag sorting stopped because your bag contents changed.",
        ["bags.sort.errorRunning"] = "Bag sorting is already running.",
        ["bags.sort.errorUnavailableClient"] = "Cannot sort bags on this client.",
        ["bags.sort.errorCursor"] = "Cannot sort bags while an item is on your cursor.",
        ["bags.sort.errorPickup"] = "Bag sorting stopped because an item could not be picked up.",
        ["bags.sort.errorMove"] = "Bag sorting stopped because an item could not be moved.",
        ["bags.sort.errorLocked"] = "Bag sorting stopped because bag {bag} slot {slot} stayed locked.",
        ["bags.lock.locked"] = "Locked {item}.",
        ["bags.lock.unlocked"] = "Unlocked {item}.",
        ["bags.lock.cannotMove"] = "Cannot move this item while it is locked.",
        ["bags.lock.cannotSell"] = "Cannot sell this item while it is locked.",
        ["bags.lock.itemFallback"] = "item {itemID}",
        ["bags.lock.itemUnknown"] = "this item",

        ["merchants.sellScraps.button"] = "Scraps",
        ["merchants.sellScraps.tooltipTitle"] = "Sell scraps",
        ["merchants.sellScraps.tooltipBody"] = "Sell {count} scrap items for {money}.",
        ["merchants.sellScraps.tooltipEmpty"] = "No sellable scraps found.",
        ["merchants.sellScraps.sold"] = "Sold scraps for {money}.",
        ["merchants.sellScraps.errorCursor"] = "Cannot sell scraps while an item is on your cursor.",
        ["merchants.scrapMark.tooltipTitle"] = "Mark scraps",
        ["merchants.scrapMark.tooltipInactive"] = "Scrap mark mode is off.",
        ["merchants.scrapMark.tooltipActive"] = "Scrap mark mode is on.",
        ["merchants.scrapMark.tooltipBody"] = "Click bag items to mark or unmark them as scraps.",
        ["merchants.scrapMark.marked"] = "Marked {item} as scrap.",
        ["merchants.scrapMark.unmarked"] = "Unmarked {item} as scrap.",
        ["merchants.scrapMark.cannotMark"] = "Cannot mark {item} as scrap.",
        ["merchants.scrapMark.itemFallback"] = "item {itemID}",
        ["merchants.scrapMark.itemUnknown"] = "this item",
        ["merchants.autoRepair.repaired"] = "Repaired equipment for {money}.",
        ["merchants.autoRepair.notEnoughMoney"] = "Cannot repair equipment ({money} required).",

        ["map.marker.tooltipTitle"] = "Custom marker",
        ["map.marker.tooltipCoordinates"] = "{x}, {y}",
        ["map.marker.tooltipCoordinatesWithDistance"] = "{x}, {y} |cff8f8f8f({distance})|r",
        ["map.marker.tooltipDistanceYards"] = "{distance} yd",
        ["map.tomtom.error.disabled"] = "TomTom-style /way commands are disabled.",
        ["map.tomtom.error.tomTomDetected"] = "TomTom is installed, so Vanilla Enhanced is not handling /way.",
        ["map.tomtom.error.invalid"] = "Use /way x y, /way zone x y, or /way #mapId x y.",
        ["map.tomtom.error.coordinates"] = "Coordinates must be between 0 and 100.",
        ["map.tomtom.error.currentMap"] = "Cannot find a current map for this waypoint.",
        ["map.tomtom.error.unknown"] = "Unknown map: {map}.",
        ["map.tomtom.error.ambiguous"] = "More than one map matches: {map}.",
        ["map.marker.added"] = "Added marker in {map} at {x}, {y}.",
        ["map.marker.removed"] = "Removed marker.",
        ["map.marker.cleared"] = "Cleared this character's map markers.",
        ["map.marker.clearConfirm"] = "Clear all custom map markers for this character?",
        ["map.marker.clearAccept"] = "Clear",
        ["map.marker.clearCancel"] = "Cancel",
        ["map.marker.unsupportedMap"] = "Cannot place a marker on this map.",
        ["map.marker.unknownMap"] = "Unknown map",

        ["quests.static.turnin"] = "Turn in",
        ["quests.static.available"] = "Available quest",
        ["quests.static.availableQuestLevel"] = "Level {level} quest available",
        ["quests.static.questLevel"] = "Quest level {level}",
        ["quests.static.requiresLevel"] = "Requires level {level}",
        ["quests.static.nearbyObjectives"] = "nearby objectives",
        ["quests.static.areaObjectives"] = "objective points in this area",
        ["quests.static.multipleObjectives"] = "Multiple objectives",
        ["quests.static.nearbyMarkers"] = "Nearby quests",
        ["quests.static.objectiveDifferentLevel"] = "Objective is on a different level.",
    },

    frFR = {
        ["module.quests"] = "Quêtes",
        ["module.map"] = "Carte",
        ["module.targetThreat"] = "Menace",
        ["module.bags"] = "Sacs",
        ["module.merchants"] = "Marchands",

        ["options.main.subtitle"] = "Active ou désactive les modules et ajuste leurs options.",
        ["options.main.locale.label"] = "Langue",
        ["options.main.locale.help"] = "Choisit la langue utilisée par Vanilla Enhanced. Auto suit la langue du client WoW quand elle est prise en charge.",
        ["options.main.locale.auto"] = "Auto",
        ["options.main.locale.auto.description"] = "Utilise le français sur les clients frFR et l’anglais sinon.",
        ["options.main.locale.enUS"] = "English",
        ["options.main.locale.enUS.description"] = "Force les textes de l’addon en anglais.",
        ["options.main.locale.frFR"] = "Français",
        ["options.main.locale.frFR.description"] = "Force les textes de l’addon en français.",
        ["options.main.chatMessagesEnabled.label"] = "Afficher les messages",
        ["options.main.chatMessagesEnabled.help"] = "Autorise les fonctions de Vanilla Enhanced à afficher les notifications et erreurs dans le chat.",
        ["options.main.showChatMessagePrefix.label"] = "Afficher le nom dans le chat",
        ["options.main.showChatMessagePrefix.help"] = "Préfixe les messages de chat avec Vanilla Enhanced.",
        ["options.main.resetSettings.label"] = "Réinitialiser",
        ["options.main.resetSettings.help"] = "Restaure toutes les options de Vanilla Enhanced à leurs valeurs par défaut.",
        ["options.main.resetSettings.confirm"] = "Réinitialiser tous les réglages de Vanilla Enhanced ?",
        ["options.main.resetSettings.accept"] = "Réinitialiser",
        ["options.main.resetSettings.cancel"] = "Annuler",
        ["options.main.resetSettings.done"] = "Réglages réinitialisés.",

        ["options.quests.subtitle"] = "Améliore le suivi des quêtes, le journal, les cartes et les infobulles.",
        ["options.quests.enable.label"] = "Activer",
        ["options.quests.enable.help"] = "Active le suivi des quêtes, la carte et les changements d'infobulles.",
        ["options.quests.keepQuestLogWithMap.label"] = "Afficher le journal avec la carte",
        ["options.quests.keepQuestLogWithMap.help"] = "Ouvre le journal des quêtes à côté de la carte du monde lorsque c'est possible.",
        ["options.quests.enableQuestTrackerClicks.label"] = "Suivi des quêtes cliquable",
        ["options.quests.enableQuestTrackerClicks.help"] = "Ouvre une quête suivie dans votre journal lorsque vous cliquez dessus.",
        ["options.quests.autoFollowQuestsMode.label"] = "Suivi automatique",
        ["options.quests.autoFollowQuestsMode.disabled"] = "Désactivé",
        ["options.quests.autoFollowQuestsMode.disabled.description"] = "Ne modifie pas la liste des quêtes suivies.",
        ["options.quests.autoFollowQuestsMode.movement"] = "Mettre à jour en déplacement",
        ["options.quests.autoFollowQuestsMode.movement.description"] = "Vérifie les quêtes actives proches pendant vos déplacements, avec une limite de distance et de fréquence.",
        ["options.quests.autoFollowQuestsMode.zone"] = "Mettre à jour au changement de zone",
        ["options.quests.autoFollowQuestsMode.zone.description"] = "Met à jour les quêtes actives proches quand votre zone ou sous-zone change.",
        ["options.quests.autoFollowQuestsMode.help"] = "Choisit quand le suivi met à jour les quêtes actives proches.",
        ["options.quests.autoFollowQuestsBehavior.label"] = "Comportement du suivi automatique",
        ["options.quests.autoFollowQuestsBehavior.replaceDistant"] = "Remplacer les quêtes lointaines",
        ["options.quests.autoFollowQuestsBehavior.replaceDistant.description"] = "Garde les quêtes proches suivies en remplaçant les quêtes suivies plus lointaines.",
        ["options.quests.autoFollowQuestsBehavior.autoOnly"] = "Gérer seulement les suivis automatiques",
        ["options.quests.autoFollowQuestsBehavior.autoOnly.description"] = "Remplace seulement les quêtes suivies automatiquement ; les suivis manuels restent en place.",
        ["options.quests.autoFollowQuestsBehavior.fillEmpty"] = "Remplir seulement les emplacements libres",
        ["options.quests.autoFollowQuestsBehavior.fillEmpty.description"] = "Ajoute des quêtes proches seulement quand le suivi a des emplacements libres.",
        ["options.quests.autoFollowQuestsBehavior.help"] = "Choisit comment le suivi automatique interagit avec les quêtes déjà suivies.",
        ["options.quests.autoFollowQuestsRange.label"] = "Portée des quêtes proches",
        ["options.quests.autoFollowQuestsRange.close"] = "Proche (600 m)",
        ["options.quests.autoFollowQuestsRange.close.description"] = "Suit automatiquement seulement les objectifs à environ 600 mètres ou moins.",
        ["options.quests.autoFollowQuestsRange.nearby"] = "À proximité (1200 m)",
        ["options.quests.autoFollowQuestsRange.nearby.description"] = "Utilise une portée équilibrée de 1200 mètres pour les objectifs proches.",
        ["options.quests.autoFollowQuestsRange.wide"] = "Large (2400 m)",
        ["options.quests.autoFollowQuestsRange.wide.description"] = "Cherche jusqu'à environ 2400 mètres, utile dans les zones peu denses.",
        ["options.quests.autoFollowQuestsRange.help"] = "Suit automatiquement seulement les quêtes dont les objectifs connus sont dans cette portée. Les quêtes sans position connue sont conservées.",
        ["options.quests.showMapMarkers.label"] = "Marqueurs de quêtes sur les cartes",
        ["options.quests.showMapMarkers.help"] = "Affiche les emplacements de quêtes sur la carte du monde et la minicarte.",
        ["options.quests.hideMapMarkersInFogOfWar.label"] = "Masquer dans le brouillard de guerre",
        ["options.quests.hideMapMarkersInFogOfWar.help"] = "Masque les marqueurs de quêtes placés dans des zones encore inexplorées.",
        ["options.quests.showSelectedQuestDirection.label"] = "Direction de la quête sélectionnée",
        ["options.quests.showSelectedQuestDirection.help"] = "Affiche l'objectif le plus proche de la quête sélectionnée sur la minicarte.",
        ["options.quests.showMinimapObjectiveAreas.label"] = "Zones d'objectifs sur la minicarte",
        ["options.quests.showMinimapObjectiveAreas.help"] = "Affiche les zones d'objectifs à tuer et à ramasser sur la minicarte.",
        ["options.quests.showRepeatableQuests.label"] = "Quêtes répétables sur les cartes",
        ["options.quests.showRepeatableQuests.help"] = "Affiche les marqueurs de quêtes répétables sur la carte du monde et la minicarte.",
        ["options.quests.showAvailableQuests.label"] = "Quêtes disponibles sur la carte",
        ["options.quests.showAvailableQuests.help"] = "Affiche sur la carte du monde les donneurs de quêtes que vous pouvez peut-être accepter.",
        ["options.quests.onlyShowNearbyAvailableQuests.label"] = "Seulement les quêtes proches",
        ["options.quests.onlyShowNearbyAvailableQuests.help"] = "Limite les marqueurs de quêtes disponibles aux donneurs situés à environ 1200 mètres de vous.",
        ["options.quests.onlyShowAvailableQuestsAroundPlayerLevel.label"] = "Seulement les quêtes de mon niveau",
        ["options.quests.onlyShowAvailableQuestsAroundPlayerLevel.help"] = "Limite les marqueurs de quêtes disponibles aux quêtes proches de votre niveau.",
        ["options.quests.availableQuestLevelsBelowPlayer.label"] = "Tranche basse",
        ["options.quests.availableQuestLevelsBelowPlayer.help"] = "Affiche les quêtes disponibles jusqu'à cette différence de niveaux avec le vôtre.",
        ["options.quests.availableQuestLevelsAbovePlayer.label"] = "Tranche haute",
        ["options.quests.availableQuestLevelsAbovePlayer.help"] = "Affiche les quêtes disponibles jusqu'à cette différence de niveaux avec le vôtre.",
        ["options.quests.showCompletedMapObjectives.label"] = "Objectifs terminés sur les cartes",
        ["options.quests.showCompletedMapObjectives.help"] = "Garde visibles les emplacements des objectifs terminés. Les lieux de rendu restent affichés.",
        ["options.quests.showCompletedTooltipObjectives.label"] = "Objectifs terminés dans les infobulles",
        ["options.quests.showCompletedTooltipObjectives.help"] = "Garde les indices d'infobulle pour les objectifs déjà terminés.",

        ["options.map.subtitle"] = "Ajoute des fonctionnalités à la carte du monde.",
        ["options.map.enable.label"] = "Activer",
        ["options.map.enable.help"] = "Active les améliorations de la carte du monde.",
        ["options.map.showWorldMapMarkers.label"] = "Marqueurs",
        ["options.map.showWorldMapMarkers.help"] = "Active les marqueurs personnalisés. Alt-clic sur la carte du monde pour en créer ou en supprimer un.",
        ["options.map.showMinimapDirections.label"] = "Minicarte",
        ["options.map.showMinimapDirections.help"] = "Affiche les marqueurs sur la minicarte et place les marqueurs lointains sur le bord.",
        ["options.map.enableTomTomCommands.label"] = "Commandes /way façon TomTom",
        ["options.map.enableTomTomCommands.help"] = "Permet à Vanilla Enhanced de gérer les coordonnées /way quand TomTom n'est pas installé. Désactivé automatiquement si TomTom est détecté.",
        ["options.map.clearMarkers.label"] = "Effacer les marqueurs",
        ["options.map.clearMarkers.help"] = "Supprime tous les marqueurs enregistrés pour ce personnage.",

        ["options.targetThreat.subtitle"] = "Affiche votre pourcentage de menace près du cadre de la cible.",
        ["options.targetThreat.enable.label"] = "Activer",
        ["options.targetThreat.enable.help"] = "Affiche votre pourcentage de menace près du cadre de la cible.",
        ["options.targetThreat.alwaysShow.label"] = "Afficher hors combat",
        ["options.targetThreat.alwaysShow.help"] = "Garde le texte de menace visible quand vous avez une cible, même hors combat.",

        ["options.bags.subtitle"] = "Ajoute des options de tri des sacs et de verrouillage d'objets.",
        ["options.bags.enable.label"] = "Activer",
        ["options.bags.enable.help"] = "Active les fonctions de tri des sacs.",
        ["options.bags.showSortButton.label"] = "Bouton de tri",
        ["options.bags.showSortButton.help"] = "Affiche un bouton de tri près du sac à dos.",
        ["options.bags.showSearchField.label"] = "Champ de recherche",
        ["options.bags.showSearchField.help"] = "Affiche un champ de recherche des sacs à côté du bouton de tri. La saisie assombrit les objets qui ne correspondent pas.",
        ["options.bags.enableItemLocking.label"] = "Verrouillage des objets",
        ["options.bags.enableItemLocking.help"] = "Alt-clic gauche sur un objet du sac pour verrouiller ou déverrouiller sa pile actuelle. Les piles verrouillées restent en place pendant le tri et ne peuvent pas être déplacées ni vendues.",
        ["options.bags.showScrapIcon.label"] = "Icône de camelote",
        ["options.bags.showScrapIcon.help"] = "Affiche une petite icône sur les objets des sacs correspondant à la stratégie de camelote du marchand.",
        ["options.bags.showScrapToggleButton.label"] = "Bouton de marquage",
        ["options.bags.showScrapToggleButton.help"] = "Affiche un bouton sur les sacs qui active le mode de marquage de la camelote. Nécessite les icônes de camelote.",
        ["options.bags.autoSortAfterLoot.label"] = "Trier après le butin",
        ["options.bags.autoSortAfterLootMode.label"] = "Mode apres butin",
        ["options.bags.autoSortAfterLootMode.tidy"] = "Rangement leger",
        ["options.bags.autoSortAfterLootMode.tidy.description"] = "Regroupe les objets récemment ramassés sans réorganiser complètement chaque groupe de sacs.",
        ["options.bags.autoSortAfterLootMode.full"] = "Tri complet",
        ["options.bags.autoSortAfterLootMode.full.description"] = "Lance le tri complet normal après le butin, avec votre ordre de tri choisi.",
        ["options.bags.autoSortAfterLootMode.help"] = "Le rangement leger regroupe les objets sans retrier completement chaque groupe. Le tri complet applique votre ordre precis apres chaque butin.",
        ["options.bags.autoSortAfterLoot.help"] = "Trie automatiquement vos sacs après la fermeture de la fenêtre de butin.",
        ["options.bags.autoSortOnOpen.label"] = "Trier à l'ouverture des sacs",
        ["options.bags.autoSortOnOpen.help"] = "Trie automatiquement vos sacs quand vous les ouvrez.",
        ["options.bags.autoOpenMode.label"] = "Ouvrir les sacs avec",
        ["options.bags.autoOpenMode.disabled"] = "Désactivé",
        ["options.bags.autoOpenMode.disabled.description"] = "Ne change pas l'ouverture des sacs.",
        ["options.bags.autoOpenMode.character"] = "Fiche de personnage",
        ["options.bags.autoOpenMode.character.description"] = "Ouvre tous les sacs quand vous ouvrez la fiche de personnage.",
        ["options.bags.autoOpenMode.merchant"] = "Marchand",
        ["options.bags.autoOpenMode.merchant.description"] = "Ouvre tous les sacs quand vous ouvrez un marchand.",
        ["options.bags.autoOpenMode.both"] = "Fiche et marchand",
        ["options.bags.autoOpenMode.both.description"] = "Ouvre tous les sacs quand vous ouvrez la fiche de personnage ou un marchand.",
        ["options.bags.autoOpenMode.help"] = "Choisit quelles fenêtres ouvrent automatiquement tous les sacs.",
        ["options.bags.sortOrder.label"] = "Trier par",
        ["options.bags.sortOrder.category"] = "Catégorie",
        ["options.bags.sortOrder.category.description"] = "Regroupe d'abord les types d'objets similaires, puis la qualité, le niveau et le nom.",
        ["options.bags.sortOrder.quality"] = "Qualité",
        ["options.bags.sortOrder.quality.description"] = "Priorise les objets de meilleure qualité et de plus haut niveau avant le type et le nom.",
        ["options.bags.sortOrder.name"] = "Nom",
        ["options.bags.sortOrder.name.description"] = "Trie d'abord par ordre alphabétique, puis utilise le type, la qualité et le niveau pour départager.",
        ["options.bags.sortOrder.help"] = "Choisit comment les objets sont triés.",

        ["options.merchants.subtitle"] = "Ajoute des outils pratiques chez les marchands.",
        ["options.merchants.enable.label"] = "Activer",
        ["options.merchants.enable.help"] = "Active les fonctions de marchand.",
        ["options.merchants.sellScraps.label"] = "Vendre la camelote",
        ["options.merchants.sellScraps.help"] = "Affiche un bouton chez les marchands pour vendre les objets inutiles.",
        ["options.merchants.autoSellScraps.label"] = "Vendre automatiquement",
        ["options.merchants.autoSellScraps.help"] = "Vend automatiquement les objets inutiles quand vous ouvrez un marchand.",
        ["options.merchants.autoRepair.label"] = "Réparer automatiquement",
        ["options.merchants.autoRepair.help"] = "Répare votre équipement quand vous ouvrez un marchand capable de réparer.",
        ["options.merchants.safeManualSell.label"] = "Vente manuelle sécurisée",
        ["options.merchants.safeManualSell.help"] = "Limite la vente manuelle à 12 piles. Quand cette option est désactivée, la vente manuelle vend tous les objets inutiles, mais certains ne peuvent pas être rachetés.",
        ["options.merchants.sortBagsAfterSellingScraps.label"] = "Trier après la vente",
        ["options.merchants.sortBagsAfterSellingScraps.help"] = "Trie les sacs apres la vente de la camelote. Necessite que le module Sacs soit actif.",
        ["options.merchants.safeAutoSell.label"] = "Vente automatique sécurisée",
        ["options.merchants.safeAutoSell.help"] = "Limite la vente automatique à 12 piles. Quand cette option est désactivée, la vente automatique vend tous les objets inutiles, mais certains ne peuvent pas être rachetés.",
        ["options.merchants.scrapStrategy.label"] = "Stratégie de camelote",
        ["options.merchants.scrapStrategy.poorSellable"] = "Objets gris vendables",
        ["options.merchants.scrapStrategy.poorSellable.description"] = "Vend les objets gris ayant un prix de vente, en laissant les objets de quête et verrouillés.",
        ["options.merchants.scrapStrategy.poorUnusableEquipment"] = "Gris + équipement inutilisable",
        ["options.merchants.scrapStrategy.poorUnusableEquipment.description"] = "Vend aussi l'équipement lié de qualité inhabituelle ou inférieure que vous ne pouvez pas utiliser.",
        ["options.merchants.scrapStrategy.poorLowConsumables"] = "Gris + consommables faibles",
        ["options.merchants.scrapStrategy.poorLowConsumables.description"] = "Vend aussi les consommables de très bas niveau, de qualité inhabituelle ou inférieure.",
        ["options.merchants.scrapStrategy.poorLowEquipment"] = "Gris + équipement faible",
        ["options.merchants.scrapStrategy.poorLowEquipment.description"] = "Vend aussi l'équipement lié de qualité inhabituelle ou inférieure, très en dessous de ce que vous portez.",
        ["options.merchants.scrapStrategy.smart"] = "Nettoyage intelligent",
        ["options.merchants.scrapStrategy.smart.description"] = "Combine toutes les règles : objets gris vendables, équipement inutilisable, consommables faibles et équipement faible.",
        ["options.merchants.scrapStrategy.help"] = "Choisit quels objets comptent comme camelote. Le nettoyage intelligent inclut aussi l'équipement lié inutilisable, les consommables très faibles et l'équipement lié bien inférieur au vôtre.",

        ["bags.sort.button"] = "Trier",
        ["bags.sort.tooltipTitle"] = "Trier les sacs",
        ["bags.sort.tooltipBody"] = "Trie votre sac à dos et vos sacs équipés.",
        ["bags.search.placeholder"] = "Rechercher",
        ["bags.search.tooltipTitle"] = "Rechercher dans les sacs",
        ["bags.search.tooltipBody"] = "Saisissez du texte pour assombrir les objets dont le nom, le type ou l'infobulle ne correspond pas.",
        ["bags.sort.errorChanged"] = "Le tri des sacs s'est arrêté parce que le contenu des sacs a changé.",
        ["bags.sort.errorRunning"] = "Le tri des sacs est déjà en cours.",
        ["bags.sort.errorUnavailableClient"] = "Impossible de trier les sacs sur ce client.",
        ["bags.sort.errorCursor"] = "Impossible de trier les sacs tant qu'un objet est sur votre curseur.",
        ["bags.sort.errorPickup"] = "Le tri des sacs s'est arrêté parce qu'un objet n'a pas pu être ramassé.",
        ["bags.sort.errorMove"] = "Le tri des sacs s'est arrêté parce qu'un objet n'a pas pu être déplacé.",
        ["bags.sort.errorLocked"] = "Le tri des sacs s'est arrêté parce que le sac {bag} emplacement {slot} est resté verrouillé.",
        ["bags.lock.locked"] = "{item} verrouillé.",
        ["bags.lock.unlocked"] = "{item} déverrouillé.",
        ["bags.lock.cannotMove"] = "Impossible de déplacer cet objet tant qu'il est verrouillé.",
        ["bags.lock.cannotSell"] = "Impossible de vendre cet objet tant qu'il est verrouillé.",
        ["bags.lock.itemFallback"] = "objet {itemID}",
        ["bags.lock.itemUnknown"] = "cet objet",

        ["merchants.sellScraps.button"] = "Vendre la camelote",
        ["merchants.sellScraps.tooltipTitle"] = "Vendre la camelote",
        ["merchants.sellScraps.tooltipBody"] = "Vend {count} objets pour {money}.",
        ["merchants.sellScraps.tooltipEmpty"] = "Aucun objet à vendre.",
        ["merchants.sellScraps.sold"] = "Camelote vendue pour {money}.",
        ["merchants.sellScraps.errorCursor"] = "Impossible de vendre la camelote tant qu'un objet est sur votre curseur.",
        ["merchants.scrapMark.tooltipTitle"] = "Marquer la camelote",
        ["merchants.scrapMark.tooltipInactive"] = "Le mode de marquage est désactivé.",
        ["merchants.scrapMark.tooltipActive"] = "Le mode de marquage est activé.",
        ["merchants.scrapMark.tooltipBody"] = "Quand activé, cliquer sur un object dans les sac le marque comme étant inutile.",
        ["merchants.scrapMark.marked"] = "{item} marqué comme camelote.",
        ["merchants.scrapMark.unmarked"] = "{item} retiré de la camelote.",
        ["merchants.scrapMark.cannotMark"] = "Impossible de marquer {item} comme camelote.",
        ["merchants.scrapMark.itemFallback"] = "objet {itemID}",
        ["merchants.scrapMark.itemUnknown"] = "cet objet",
        ["merchants.autoRepair.repaired"] = "Équipement réparé pour {money}.",
        ["merchants.autoRepair.notEnoughMoney"] = "Impossible de réparer l'équipement ({money} requis).",

        ["map.marker.tooltipTitle"] = "Marqueur",
        ["map.marker.tooltipCoordinates"] = "{x}, {y}",
        ["map.marker.tooltipCoordinatesWithDistance"] = "{x}, {y} |cff8f8f8f({distance})|r",
        ["map.marker.tooltipDistanceYards"] = "à {distance} mètres",
        ["map.tomtom.error.disabled"] = "Les commandes /way façon TomTom sont désactivées.",
        ["map.tomtom.error.tomTomDetected"] = "TomTom est installé, Vanilla Enhanced ne gère donc pas /way.",
        ["map.tomtom.error.invalid"] = "Utilisez /way x y, /way zone x y ou /way #idCarte x y.",
        ["map.tomtom.error.coordinates"] = "Les coordonnées doivent être comprises entre 0 et 100.",
        ["map.tomtom.error.currentMap"] = "Impossible de trouver une carte actuelle pour ce repère.",
        ["map.tomtom.error.unknown"] = "Carte inconnue : {map}.",
        ["map.tomtom.error.ambiguous"] = "Plusieurs cartes correspondent : {map}.",
        ["map.marker.added"] = "Marqueur ajouté dans {map} à {x}, {y}.",
        ["map.marker.removed"] = "Marqueur supprimé.",
        ["map.marker.cleared"] = "Marqueurs de carte effacés pour ce personnage.",
        ["map.marker.clearConfirm"] = "Effacer tous les marqueurs personnalisés de ce personnage ?",
        ["map.marker.clearAccept"] = "Effacer",
        ["map.marker.clearCancel"] = "Annuler",
        ["map.marker.unsupportedMap"] = "Impossible de placer un marqueur sur cette carte.",
        ["map.marker.unknownMap"] = "Carte inconnue",

        ["quests.static.turnin"] = "Rendre la quête",
        ["quests.static.available"] = "Quête disponible",
        ["quests.static.availableQuestLevel"] = "Quête de niveau {level} disponible",
        ["quests.static.questLevel"] = "Niveau de quête {level}",
        ["quests.static.requiresLevel"] = "Niveau {level} requis",
        ["quests.static.nearbyObjectives"] = "objectifs proches",
        ["quests.static.areaObjectives"] = "points d'objectif dans cette zone",
        ["quests.static.multipleObjectives"] = "Objectifs multiples",
        ["quests.static.nearbyMarkers"] = "Quêtes proches",
        ["quests.static.objectiveDifferentLevel"] = "L'objectif est à un autre étage.",
    },
}

VanillaEnhanced.localeStrings = STRINGS

local IMPLEMENTED_LOCALES = { "enUS", "frFR" }
local SUPPORTED_LOCALES = {}

for _, locale in ipairs(IMPLEMENTED_LOCALES) do
    SUPPORTED_LOCALES[locale] = true
end

local function GetAutoLocaleKey()
    local locale = type(GetLocale) == "function" and GetLocale() or "enUS"
    return locale == "frFR" and "frFR" or "enUS"
end

function VanillaEnhanced:GetLocaleKey()
    local settings = self.GetSettings and self:GetSettings() or nil
    local locale = settings and settings.locale or "auto"
    if locale ~= "auto" and SUPPORTED_LOCALES[locale] then
        return locale
    end
    return GetAutoLocaleKey()
end

function VanillaEnhanced:SetLocaleKey(locale)
    if locale ~= "auto" and not SUPPORTED_LOCALES[locale] then
        locale = "auto"
    end

    local settings = self:GetSettings()
    settings.locale = locale
    return settings.locale
end

function VanillaEnhanced:GetLocaleOptions()
    local options = {
        {
            value = "auto",
            labelKey = "options.main.locale.auto",
            descriptionKey = "options.main.locale.auto.description",
        },
    }

    for _, locale in ipairs(IMPLEMENTED_LOCALES) do
        options[#options + 1] = {
            value = locale,
            labelKey = "options.main.locale." .. locale,
            descriptionKey = "options.main.locale." .. locale .. ".description",
        }
    end

    return options
end

local function Lookup(locale, key)
    local strings = STRINGS[locale]
    return strings and strings[key] or nil
end

function VanillaEnhanced:T(key, vars)
    local text = Lookup(self:GetLocaleKey(), key) or Lookup("enUS", key) or key
    if type(vars) ~= "table" then
        return text
    end

    local localized = string.gsub(text, "{([%w_]+)}", function(name)
        local value = vars[name]
        if value == nil then
            return "{" .. name .. "}"
        end
        return tostring(value)
    end)
    return localized
end
