export type ProfessionRecipeSource = {
  meta?: {
    source?: string;
    expansion?: string;
  };
  recipes: ProfessionRecipeSourceEntry[];
};

export type ProfessionRecipeSourceEntry = {
  spellID: number;
  professionID: number;
  skill?: number;
  reagents: [number, number][];
};

export type ProfessionRecipeEntry = {
  spellID: number;
  professionID: number;
  skill: number;
  quantity: number;
};

export type ProfessionRecipeArtifacts = {
  lua: string;
  reagentCount: number;
  recipeCount: number;
};

const VALID_PROFESSIONS = new Set([129, 164, 165, 171, 185, 186, 197, 202, 333, 755]);

function assertInteger(value: unknown, label: string, errors: string[]): number | undefined {
  if (typeof value !== "number" || !Number.isFinite(value) || Math.trunc(value) !== value || value <= 0) {
    errors.push(`${label} must be a positive integer`);
    return undefined;
  }
  return value;
}

function luaString(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\r/g, "").replace(/\n/g, "\\n")}"`;
}

function formatMeta(meta: ProfessionRecipeSource["meta"] | undefined, reagentCount: number, recipeCount: number): string {
  const fields = [
    `source = ${luaString(meta?.source ?? "Vanilla Enhanced profession recipe data")}`,
    `expansion = ${luaString(meta?.expansion ?? "TBC")}`,
    `reagentCount = ${reagentCount}`,
    `recipeCount = ${recipeCount}`,
  ];
  return `{ ${fields.join(", ")} }`;
}

function formatEntry(entry: ProfessionRecipeEntry): string {
  const fields = [`s=${entry.spellID}`, `p=${entry.professionID}`, `q=${entry.quantity}`];
  if (entry.skill > 0) fields.push(`r=${entry.skill}`);
  return `{${fields.join(",")}}`;
}

export function buildProfessionRecipeArtifacts(input: ProfessionRecipeSource): ProfessionRecipeArtifacts {
  const errors: string[] = [];
  if (!input || typeof input !== "object" || !Array.isArray(input.recipes)) {
    throw new Error("Profession recipe source must contain a recipes array.");
  }

  const byReagent = new Map<number, ProfessionRecipeEntry[]>();
  const seenRecipes = new Set<number>();

  input.recipes.forEach((recipe, index) => {
    const context = `recipes[${index}]`;
    const spellID = assertInteger(recipe.spellID, `${context}.spellID`, errors);
    const professionID = assertInteger(recipe.professionID, `${context}.professionID`, errors);
    const skill = recipe.skill === undefined ? 0 : assertInteger(recipe.skill, `${context}.skill`, errors);

    if (professionID && !VALID_PROFESSIONS.has(professionID)) {
      errors.push(`${context}.professionID ${professionID} is not a supported TBC recipe profession`);
    }
    if (!Array.isArray(recipe.reagents) || recipe.reagents.length === 0) {
      errors.push(`${context}.reagents must contain at least one reagent`);
      return;
    }
    if (spellID) {
      if (seenRecipes.has(spellID)) errors.push(`${context}.spellID ${spellID} is duplicated`);
      seenRecipes.add(spellID);
    }

    for (const reagent of recipe.reagents) {
      if (!Array.isArray(reagent) || reagent.length !== 2) {
        errors.push(`${context}.reagents contains a malformed reagent pair`);
        continue;
      }
      const reagentID = assertInteger(reagent[0], `${context}.reagentID`, errors);
      const quantity = assertInteger(reagent[1], `${context}.quantity`, errors);
      if (!spellID || !professionID || skill === undefined || !reagentID || !quantity) continue;

      const entries = byReagent.get(reagentID) ?? [];
      entries.push({ spellID, professionID, skill, quantity });
      byReagent.set(reagentID, entries);
    }
  });

  if (errors.length) {
    throw new Error(`Profession recipe data validation failed:\n${errors.join("\n")}`);
  }

  for (const entries of byReagent.values()) {
    entries.sort((left, right) =>
      left.professionID - right.professionID ||
      left.skill - right.skill ||
      left.spellID - right.spellID ||
      left.quantity - right.quantity
    );
  }

  const lines = [
    "-- AUTO GENERATED by tools/professions/build.ts. Do not edit by hand.",
    "VanillaEnhancedProfessionRecipesDB = {",
    `  meta = ${formatMeta(input.meta, byReagent.size, seenRecipes.size)},`,
    "  reagents = {",
  ];

  for (const reagentID of [...byReagent.keys()].sort((left, right) => left - right)) {
    lines.push(`    [${reagentID}] = {${byReagent.get(reagentID)!.map(formatEntry).join(",")}},`);
  }

  lines.push("  }", "}", "");

  return {
    lua: lines.join("\n"),
    reagentCount: byReagent.size,
    recipeCount: seenRecipes.size,
  };
}
